//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
	[Window(UILayer.UI, location : "LoginUI")]
	public partial class LoginUI : UIWindow
	{
		#region 脚本工具生成的代码

		private UIBindComponent m_bindComponent;
		private InputField m_inputAccount = null!;
		private Button m_btnLogin = null!;

		protected override void ScriptGenerator()
		{
			m_bindComponent = gameObject.GetComponent<UIBindComponent>();
			m_inputAccount = m_bindComponent.GetComponent<InputField>(0);
			m_btnLogin = m_bindComponent.GetComponent<Button>(1);
			m_btnLogin.onClick.AddListener(OnClickLoginBtn);
		}

		#endregion


		#region 事件

		private void OnClickLoginBtn()
        {
			if (GameModule.Net.IsConnected)
			{		
				C2sSprotoType.checkAccount.request request = new C2sSprotoType.checkAccount.request();
				request.token = "93";
				request.lid = "93";
				request.platformuid = "Windows PC";
				request.shareQuery = "";
				request.wxuserinfo = "";
                GameModule.Net.Send<C2sProtocol.checkAccount>(request, (rsp) =>
				{
					Debug.Log("Login response received");
					if (rsp != null)
					{
						Debug.Log($"Login successful: {rsp}");
					}
				});
				return;
			}
			else
            {
            	Log.Info($"点击登录按钮：");
				GameModule.Net.Connect(
					 //"10.0.0.119",
					 //5204,
					 "192.168.136.130",
					 5001,
					"ws",
					() => { 
						Log.Info("连接服务器成功");
					},
					() => { Log.Info("连接服务器失败"); }
				);   
            }
        }

		#endregion
	}
}
