//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
	public partial class MessageBox : UIWindow
	{
		#region 脚本工具生成的代码

		private UIBindComponent m_bindComponent;
		private Button m_btnOk = null!;
		private Button m_btnClose = null!;
		private Button m_btnCancel = null!;
		private Text m_textMsg = null!;
		private Text m_textTitle = null!;

		protected override void ScriptGenerator()
		{
			m_bindComponent = gameObject.GetComponent<UIBindComponent>();
			m_btnOk = m_bindComponent.GetComponent<Button>(0);
			m_btnClose = m_bindComponent.GetComponent<Button>(1);
			m_btnCancel = m_bindComponent.GetComponent<Button>(2);
			m_textMsg = m_bindComponent.GetComponent<Text>(3);
			m_textTitle = m_bindComponent.GetComponent<Text>(4);
			m_btnOk.onClick.AddListener(OnClickOkBtn);
			m_btnClose.onClick.AddListener(OnClickCloseBtn);
			m_btnCancel.onClick.AddListener(OnClickCancelBtn);
		}

		#endregion

		#region 事件

		private void OnClickOkBtn()
        {
            
        }

		private  void OnClickCloseBtn()
        {
            
        }

		private void OnClickCancelBtn()
        {
            
        }

		#endregion
		
	}
}
