// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class C2sProtocol : ProtocolBase {
	public static  C2sProtocol Instance = new C2sProtocol();
	private C2sProtocol() {
		Protocol.SetProtocol<ActorCount> (ActorCount.Tag);
		Protocol.SetRequest<C2sSprotoType.ActorCount.request> (ActorCount.Tag);
		Protocol.SetResponse<C2sSprotoType.ActorCount.response> (ActorCount.Tag);

		Protocol.SetProtocol<CreateActor> (CreateActor.Tag);
		Protocol.SetRequest<C2sSprotoType.CreateActor.request> (CreateActor.Tag);
		Protocol.SetResponse<C2sSprotoType.CreateActor.response> (CreateActor.Tag);

		Protocol.SetProtocol<DelayActorCreate> (DelayActorCreate.Tag);
		Protocol.SetRequest<C2sSprotoType.DelayActorCreate.request> (DelayActorCreate.Tag);
		Protocol.SetResponse<C2sSprotoType.DelayActorCreate.response> (DelayActorCreate.Tag);

		Protocol.SetProtocol<EnterGame> (EnterGame.Tag);
		Protocol.SetRequest<C2sSprotoType.EnterGame.request> (EnterGame.Tag);
		Protocol.SetResponse<C2sSprotoType.EnterGame.response> (EnterGame.Tag);

		Protocol.SetProtocol<LockName> (LockName.Tag);
		Protocol.SetRequest<C2sSprotoType.LockName.request> (LockName.Tag);
		Protocol.SetResponse<C2sSprotoType.LockName.response> (LockName.Tag);

		Protocol.SetProtocol<QueryList> (QueryList.Tag);
		Protocol.SetRequest<C2sSprotoType.QueryList.request> (QueryList.Tag);
		Protocol.SetResponse<C2sSprotoType.QueryList.response> (QueryList.Tag);

		Protocol.SetProtocol<RandName> (RandName.Tag);
		Protocol.SetRequest<C2sSprotoType.RandName.request> (RandName.Tag);
		Protocol.SetResponse<C2sSprotoType.RandName.response> (RandName.Tag);

		Protocol.SetProtocol<Rename> (Rename.Tag);
		Protocol.SetRequest<C2sSprotoType.Rename.request> (Rename.Tag);
		Protocol.SetResponse<C2sSprotoType.Rename.response> (Rename.Tag);

		Protocol.SetProtocol<checkAccount> (checkAccount.Tag);
		Protocol.SetRequest<C2sSprotoType.checkAccount.request> (checkAccount.Tag);
		Protocol.SetResponse<C2sSprotoType.checkAccount.response> (checkAccount.Tag);

		Protocol.SetProtocol<cs_base_get_game_time> (cs_base_get_game_time.Tag);

		Protocol.SetProtocol<cs_club_create> (cs_club_create.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_club_create.request> (cs_club_create.Tag);

		Protocol.SetProtocol<cs_club_join> (cs_club_join.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_club_join.request> (cs_club_join.Tag);

		Protocol.SetProtocol<cs_club_process_apply> (cs_club_process_apply.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_club_process_apply.request> (cs_club_process_apply.Tag);

		Protocol.SetProtocol<cs_club_quit> (cs_club_quit.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_club_quit.request> (cs_club_quit.Tag);

		Protocol.SetProtocol<cs_club_require_apply_list> (cs_club_require_apply_list.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_club_require_apply_list.request> (cs_club_require_apply_list.Tag);

		Protocol.SetProtocol<cs_club_require_members> (cs_club_require_members.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_club_require_members.request> (cs_club_require_members.Tag);

		Protocol.SetProtocol<cs_eliminate_exit> (cs_eliminate_exit.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_eliminate_exit.request> (cs_eliminate_exit.Tag);

		Protocol.SetProtocol<cs_eliminate_practice> (cs_eliminate_practice.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_eliminate_practice.request> (cs_eliminate_practice.Tag);

		Protocol.SetProtocol<cs_eliminate_reconnect> (cs_eliminate_reconnect.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_eliminate_reconnect.request> (cs_eliminate_reconnect.Tag);

		Protocol.SetProtocol<cs_eliminate_switch> (cs_eliminate_switch.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_eliminate_switch.request> (cs_eliminate_switch.Tag);

		Protocol.SetProtocol<cs_eliminate_use_skill> (cs_eliminate_use_skill.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_eliminate_use_skill.request> (cs_eliminate_use_skill.Tag);

		Protocol.SetProtocol<cs_room_cancelmatch> (cs_room_cancelmatch.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_room_cancelmatch.request> (cs_room_cancelmatch.Tag);
		Protocol.SetResponse<C2sSprotoType.cs_room_cancelmatch.response> (cs_room_cancelmatch.Tag);

		Protocol.SetProtocol<cs_room_create> (cs_room_create.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_room_create.request> (cs_room_create.Tag);

		Protocol.SetProtocol<cs_room_enter> (cs_room_enter.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_room_enter.request> (cs_room_enter.Tag);
		Protocol.SetResponse<C2sSprotoType.cs_room_enter.response> (cs_room_enter.Tag);

		Protocol.SetProtocol<cs_room_exit> (cs_room_exit.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_room_exit.request> (cs_room_exit.Tag);
		Protocol.SetResponse<C2sSprotoType.cs_room_exit.response> (cs_room_exit.Tag);

		Protocol.SetProtocol<cs_room_kick> (cs_room_kick.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_room_kick.request> (cs_room_kick.Tag);
		Protocol.SetResponse<C2sSprotoType.cs_room_kick.response> (cs_room_kick.Tag);

		Protocol.SetProtocol<cs_room_list> (cs_room_list.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_room_list.request> (cs_room_list.Tag);

		Protocol.SetProtocol<cs_room_match> (cs_room_match.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_room_match.request> (cs_room_match.Tag);
		Protocol.SetResponse<C2sSprotoType.cs_room_match.response> (cs_room_match.Tag);

		Protocol.SetProtocol<cs_room_ready> (cs_room_ready.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_room_ready.request> (cs_room_ready.Tag);
		Protocol.SetResponse<C2sSprotoType.cs_room_ready.response> (cs_room_ready.Tag);

		Protocol.SetProtocol<cs_room_reenter> (cs_room_reenter.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_room_reenter.request> (cs_room_reenter.Tag);
		Protocol.SetResponse<C2sSprotoType.cs_room_reenter.response> (cs_room_reenter.Tag);

		Protocol.SetProtocol<cs_room_start> (cs_room_start.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_room_start.request> (cs_room_start.Tag);
		Protocol.SetResponse<C2sSprotoType.cs_room_start.response> (cs_room_start.Tag);

		Protocol.SetProtocol<cs_send_heart_beat> (cs_send_heart_beat.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_send_heart_beat.request> (cs_send_heart_beat.Tag);

		Protocol.SetProtocol<cs_sene_gm_command> (cs_sene_gm_command.Tag);
		Protocol.SetRequest<C2sSprotoType.cs_sene_gm_command.request> (cs_sene_gm_command.Tag);

		Protocol.SetProtocol<gameplayc2s_archiveGainReward> (gameplayc2s_archiveGainReward.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_archiveGainReward.request> (gameplayc2s_archiveGainReward.Tag);

		Protocol.SetProtocol<gameplayc2s_box> (gameplayc2s_box.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_box.request> (gameplayc2s_box.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_box.response> (gameplayc2s_box.Tag);

		Protocol.SetProtocol<gameplayc2s_buyItem> (gameplayc2s_buyItem.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_buyItem.request> (gameplayc2s_buyItem.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_buyItem.response> (gameplayc2s_buyItem.Tag);

		Protocol.SetProtocol<gameplayc2s_cashOut> (gameplayc2s_cashOut.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_cashOut.request> (gameplayc2s_cashOut.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_cashOut.response> (gameplayc2s_cashOut.Tag);

		Protocol.SetProtocol<gameplayc2s_composeAvartar> (gameplayc2s_composeAvartar.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_composeAvartar.request> (gameplayc2s_composeAvartar.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_composeAvartar.response> (gameplayc2s_composeAvartar.Tag);

		Protocol.SetProtocol<gameplayc2s_composeSuperAvatar> (gameplayc2s_composeSuperAvatar.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_composeSuperAvatar.request> (gameplayc2s_composeSuperAvatar.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_composeSuperAvatar.response> (gameplayc2s_composeSuperAvatar.Tag);

		Protocol.SetProtocol<gameplayc2s_createAvartar> (gameplayc2s_createAvartar.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_createAvartar.request> (gameplayc2s_createAvartar.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_createAvartar.response> (gameplayc2s_createAvartar.Tag);

		Protocol.SetProtocol<gameplayc2s_deleteMail> (gameplayc2s_deleteMail.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_deleteMail.request> (gameplayc2s_deleteMail.Tag);

		Protocol.SetProtocol<gameplayc2s_gainBonusData> (gameplayc2s_gainBonusData.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_gainBonusData.request> (gameplayc2s_gainBonusData.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_gainBonusData.response> (gameplayc2s_gainBonusData.Tag);

		Protocol.SetProtocol<gameplayc2s_gainGold> (gameplayc2s_gainGold.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_gainGold.request> (gameplayc2s_gainGold.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_gainGold.response> (gameplayc2s_gainGold.Tag);

		Protocol.SetProtocol<gameplayc2s_gainHongBao> (gameplayc2s_gainHongBao.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_gainHongBao.request> (gameplayc2s_gainHongBao.Tag);

		Protocol.SetProtocol<gameplayc2s_gainHongBaoYu> (gameplayc2s_gainHongBaoYu.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_gainHongBaoYu.request> (gameplayc2s_gainHongBaoYu.Tag);

		Protocol.SetProtocol<gameplayc2s_gainShareTaskReward> (gameplayc2s_gainShareTaskReward.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_gainShareTaskReward.request> (gameplayc2s_gainShareTaskReward.Tag);

		Protocol.SetProtocol<gameplayc2s_gainTaskReward> (gameplayc2s_gainTaskReward.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_gainTaskReward.request> (gameplayc2s_gainTaskReward.Tag);

		Protocol.SetProtocol<gameplayc2s_gainVipReward> (gameplayc2s_gainVipReward.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_gainVipReward.request> (gameplayc2s_gainVipReward.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_gainVipReward.response> (gameplayc2s_gainVipReward.Tag);

		Protocol.SetProtocol<gameplayc2s_gmRecharge> (gameplayc2s_gmRecharge.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_gmRecharge.request> (gameplayc2s_gmRecharge.Tag);

		Protocol.SetProtocol<gameplayc2s_hongbaoyu> (gameplayc2s_hongbaoyu.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_hongbaoyu.request> (gameplayc2s_hongbaoyu.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_hongbaoyu.response> (gameplayc2s_hongbaoyu.Tag);

		Protocol.SetProtocol<gameplayc2s_inputPayAddr> (gameplayc2s_inputPayAddr.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_inputPayAddr.request> (gameplayc2s_inputPayAddr.Tag);

		Protocol.SetProtocol<gameplayc2s_inputShareCode> (gameplayc2s_inputShareCode.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_inputShareCode.request> (gameplayc2s_inputShareCode.Tag);

		Protocol.SetProtocol<gameplayc2s_openBox> (gameplayc2s_openBox.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_openBox.request> (gameplayc2s_openBox.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_openBox.response> (gameplayc2s_openBox.Tag);

		Protocol.SetProtocol<gameplayc2s_rankData> (gameplayc2s_rankData.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_rankData.request> (gameplayc2s_rankData.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_rankData.response> (gameplayc2s_rankData.Tag);

		Protocol.SetProtocol<gameplayc2s_readMail> (gameplayc2s_readMail.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_readMail.request> (gameplayc2s_readMail.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_readMail.response> (gameplayc2s_readMail.Tag);

		Protocol.SetProtocol<gameplayc2s_recycle> (gameplayc2s_recycle.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_recycle.request> (gameplayc2s_recycle.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_recycle.response> (gameplayc2s_recycle.Tag);

		Protocol.SetProtocol<gameplayc2s_searchName> (gameplayc2s_searchName.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_searchName.request> (gameplayc2s_searchName.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_searchName.response> (gameplayc2s_searchName.Tag);

		Protocol.SetProtocol<gameplayc2s_sendMail> (gameplayc2s_sendMail.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_sendMail.request> (gameplayc2s_sendMail.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_sendMail.response> (gameplayc2s_sendMail.Tag);

		Protocol.SetProtocol<gameplayc2s_shareFinish> (gameplayc2s_shareFinish.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_shareFinish.request> (gameplayc2s_shareFinish.Tag);

		Protocol.SetProtocol<gameplayc2s_speedup> (gameplayc2s_speedup.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_speedup.request> (gameplayc2s_speedup.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_speedup.response> (gameplayc2s_speedup.Tag);

		Protocol.SetProtocol<gameplayc2s_watchAD> (gameplayc2s_watchAD.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_watchAD.request> (gameplayc2s_watchAD.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_watchAD.response> (gameplayc2s_watchAD.Tag);

		Protocol.SetProtocol<gameplayc2s_watchEndAD> (gameplayc2s_watchEndAD.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_watchEndAD.request> (gameplayc2s_watchEndAD.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_watchEndAD.response> (gameplayc2s_watchEndAD.Tag);

		Protocol.SetProtocol<gameplayc2s_wheel> (gameplayc2s_wheel.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_wheel.request> (gameplayc2s_wheel.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_wheel.response> (gameplayc2s_wheel.Tag);

		Protocol.SetProtocol<gameplayc2s_work> (gameplayc2s_work.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_work.request> (gameplayc2s_work.Tag);

		Protocol.SetProtocol<gameplayc2s_workReward> (gameplayc2s_workReward.Tag);
		Protocol.SetRequest<C2sSprotoType.gameplayc2s_workReward.request> (gameplayc2s_workReward.Tag);
		Protocol.SetResponse<C2sSprotoType.gameplayc2s_workReward.response> (gameplayc2s_workReward.Tag);

	}

	public class ActorCount {
		public const int Tag = 8;
	}

	public class CreateActor {
		public const int Tag = 4;
	}

	public class DelayActorCreate {
		public const int Tag = 9;
	}

	public class EnterGame {
		public const int Tag = 3;
	}

	public class LockName {
		public const int Tag = 7;
	}

	public class QueryList {
		public const int Tag = 2;
	}

	public class RandName {
		public const int Tag = 5;
	}

	public class Rename {
		public const int Tag = 10;
	}

	public class checkAccount {
		public const int Tag = 1;
	}

	public class cs_base_get_game_time {
		public const int Tag = 6;
	}

	public class cs_club_create {
		public const int Tag = 500;
	}

	public class cs_club_join {
		public const int Tag = 501;
	}

	public class cs_club_process_apply {
		public const int Tag = 503;
	}

	public class cs_club_quit {
		public const int Tag = 502;
	}

	public class cs_club_require_apply_list {
		public const int Tag = 505;
	}

	public class cs_club_require_members {
		public const int Tag = 504;
	}

	public class cs_eliminate_exit {
		public const int Tag = 403;
	}

	public class cs_eliminate_practice {
		public const int Tag = 404;
	}

	public class cs_eliminate_reconnect {
		public const int Tag = 402;
	}

	public class cs_eliminate_switch {
		public const int Tag = 400;
	}

	public class cs_eliminate_use_skill {
		public const int Tag = 401;
	}

	public class cs_room_cancelmatch {
		public const int Tag = 307;
	}

	public class cs_room_create {
		public const int Tag = 301;
	}

	public class cs_room_enter {
		public const int Tag = 302;
	}

	public class cs_room_exit {
		public const int Tag = 303;
	}

	public class cs_room_kick {
		public const int Tag = 308;
	}

	public class cs_room_list {
		public const int Tag = 300;
	}

	public class cs_room_match {
		public const int Tag = 304;
	}

	public class cs_room_ready {
		public const int Tag = 305;
	}

	public class cs_room_reenter {
		public const int Tag = 309;
	}

	public class cs_room_start {
		public const int Tag = 306;
	}

	public class cs_send_heart_beat {
		public const int Tag = 199;
	}

	public class cs_sene_gm_command {
		public const int Tag = 100;
	}

	public class gameplayc2s_archiveGainReward {
		public const int Tag = 105;
	}

	public class gameplayc2s_box {
		public const int Tag = 116;
	}

	public class gameplayc2s_buyItem {
		public const int Tag = 112;
	}

	public class gameplayc2s_cashOut {
		public const int Tag = 121;
	}

	public class gameplayc2s_composeAvartar {
		public const int Tag = 102;
	}

	public class gameplayc2s_composeSuperAvatar {
		public const int Tag = 126;
	}

	public class gameplayc2s_createAvartar {
		public const int Tag = 101;
	}

	public class gameplayc2s_deleteMail {
		public const int Tag = 132;
	}

	public class gameplayc2s_gainBonusData {
		public const int Tag = 119;
	}

	public class gameplayc2s_gainGold {
		public const int Tag = 111;
	}

	public class gameplayc2s_gainHongBao {
		public const int Tag = 120;
	}

	public class gameplayc2s_gainHongBaoYu {
		public const int Tag = 125;
	}

	public class gameplayc2s_gainShareTaskReward {
		public const int Tag = 117;
	}

	public class gameplayc2s_gainTaskReward {
		public const int Tag = 108;
	}

	public class gameplayc2s_gainVipReward {
		public const int Tag = 130;
	}

	public class gameplayc2s_gmRecharge {
		public const int Tag = 131;
	}

	public class gameplayc2s_hongbaoyu {
		public const int Tag = 114;
	}

	public class gameplayc2s_inputPayAddr {
		public const int Tag = 123;
	}

	public class gameplayc2s_inputShareCode {
		public const int Tag = 122;
	}

	public class gameplayc2s_openBox {
		public const int Tag = 115;
	}

	public class gameplayc2s_rankData {
		public const int Tag = 124;
	}

	public class gameplayc2s_readMail {
		public const int Tag = 129;
	}

	public class gameplayc2s_recycle {
		public const int Tag = 110;
	}

	public class gameplayc2s_searchName {
		public const int Tag = 127;
	}

	public class gameplayc2s_sendMail {
		public const int Tag = 128;
	}

	public class gameplayc2s_shareFinish {
		public const int Tag = 118;
	}

	public class gameplayc2s_speedup {
		public const int Tag = 109;
	}

	public class gameplayc2s_watchAD {
		public const int Tag = 106;
	}

	public class gameplayc2s_watchEndAD {
		public const int Tag = 107;
	}

	public class gameplayc2s_wheel {
		public const int Tag = 113;
	}

	public class gameplayc2s_work {
		public const int Tag = 103;
	}

	public class gameplayc2s_workReward {
		public const int Tag = 104;
	}

}