// Generated by sprotodump. DO NOT EDIT!
// source: F:\new\unity\TEngine\Tools\sproto/../../Configs/Sproto/club_s2c.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace S2cSprotoType { 
	public class club_applyinfo : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _dbid; // tag 0
		public Int64 dbid {
			get { return _dbid; }
			set { base.has_field.set_field (0, true); _dbid = value; }
		}
		public bool HasDbid {
			get { return base.has_field.has_field (0); }
		}

		private string _name; // tag 1
		public string name {
			get { return _name; }
			set { base.has_field.set_field (1, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (1); }
		}

		private string _head; // tag 2
		public string head {
			get { return _head; }
			set { base.has_field.set_field (2, true); _head = value; }
		}
		public bool HasHead {
			get { return base.has_field.has_field (2); }
		}

		public club_applyinfo () : base(max_field_count) {}

		public club_applyinfo (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.dbid = base.deserialize.read_integer ();
					break;
				case 1:
					this.name = base.deserialize.read_string ();
					break;
				case 2:
					this.head = base.deserialize.read_string ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.dbid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.name, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_string (this.head, 2);
			}

			return base.serialize.close ();
		}
	}


	public class club_memberinfo : SprotoTypeBase {
		private static int max_field_count = 5;
		
		
		private Int64 _dbid; // tag 0
		public Int64 dbid {
			get { return _dbid; }
			set { base.has_field.set_field (0, true); _dbid = value; }
		}
		public bool HasDbid {
			get { return base.has_field.has_field (0); }
		}

		private string _name; // tag 1
		public string name {
			get { return _name; }
			set { base.has_field.set_field (1, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _office; // tag 2
		public Int64 office {
			get { return _office; }
			set { base.has_field.set_field (2, true); _office = value; }
		}
		public bool HasOffice {
			get { return base.has_field.has_field (2); }
		}

		private string _head; // tag 3
		public string head {
			get { return _head; }
			set { base.has_field.set_field (3, true); _head = value; }
		}
		public bool HasHead {
			get { return base.has_field.has_field (3); }
		}

		private bool _online; // tag 4
		public bool online {
			get { return _online; }
			set { base.has_field.set_field (4, true); _online = value; }
		}
		public bool HasOnline {
			get { return base.has_field.has_field (4); }
		}

		public club_memberinfo () : base(max_field_count) {}

		public club_memberinfo (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.dbid = base.deserialize.read_integer ();
					break;
				case 1:
					this.name = base.deserialize.read_string ();
					break;
				case 2:
					this.office = base.deserialize.read_integer ();
					break;
				case 3:
					this.head = base.deserialize.read_string ();
					break;
				case 4:
					this.online = base.deserialize.read_boolean ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.dbid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.name, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.office, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_string (this.head, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_boolean (this.online, 4);
			}

			return base.serialize.close ();
		}
	}


	public class club_simpleinfo : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _dbid; // tag 0
		public Int64 dbid {
			get { return _dbid; }
			set { base.has_field.set_field (0, true); _dbid = value; }
		}
		public bool HasDbid {
			get { return base.has_field.has_field (0); }
		}

		private string _name; // tag 1
		public string name {
			get { return _name; }
			set { base.has_field.set_field (1, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (1); }
		}

		private club_memberinfo _leader; // tag 2
		public club_memberinfo leader {
			get { return _leader; }
			set { base.has_field.set_field (2, true); _leader = value; }
		}
		public bool HasLeader {
			get { return base.has_field.has_field (2); }
		}

		public club_simpleinfo () : base(max_field_count) {}

		public club_simpleinfo (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.dbid = base.deserialize.read_integer ();
					break;
				case 1:
					this.name = base.deserialize.read_string ();
					break;
				case 2:
					this.leader = base.deserialize.read_obj<club_memberinfo> ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.dbid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.name, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_obj (this.leader, 2);
			}

			return base.serialize.close ();
		}
	}


	public class sc_club_apply_list {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _clubid; // tag 0
			public Int64 clubid {
				get { return _clubid; }
				set { base.has_field.set_field (0, true); _clubid = value; }
			}
			public bool HasClubid {
				get { return base.has_field.has_field (0); }
			}

			private List<club_applyinfo> _applys; // tag 1
			public List<club_applyinfo> applys {
				get { return _applys; }
				set { base.has_field.set_field (1, true); _applys = value; }
			}
			public bool HasApplys {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubid = base.deserialize.read_integer ();
						break;
					case 1:
						this.applys = base.deserialize.read_obj_list<club_applyinfo> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.clubid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.applys, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_club_apply_ret {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _ret; // tag 0
			public Int64 ret {
				get { return _ret; }
				set { base.has_field.set_field (0, true); _ret = value; }
			}
			public bool HasRet {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.ret = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.ret, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_club_create_ret {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _ret; // tag 0
			public Int64 ret {
				get { return _ret; }
				set { base.has_field.set_field (0, true); _ret = value; }
			}
			public bool HasRet {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.ret = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.ret, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_club_infolist {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<club_simpleinfo> _clubs; // tag 0
			public List<club_simpleinfo> clubs {
				get { return _clubs; }
				set { base.has_field.set_field (0, true); _clubs = value; }
			}
			public bool HasClubs {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubs = base.deserialize.read_obj_list<club_simpleinfo> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.clubs, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_club_join {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _clubid; // tag 0
			public Int64 clubid {
				get { return _clubid; }
				set { base.has_field.set_field (0, true); _clubid = value; }
			}
			public bool HasClubid {
				get { return base.has_field.has_field (0); }
			}

			private club_simpleinfo _info; // tag 1
			public club_simpleinfo info {
				get { return _info; }
				set { base.has_field.set_field (1, true); _info = value; }
			}
			public bool HasInfo {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubid = base.deserialize.read_integer ();
						break;
					case 1:
						this.info = base.deserialize.read_obj<club_simpleinfo> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.clubid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.info, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_club_member_list {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _clubid; // tag 0
			public Int64 clubid {
				get { return _clubid; }
				set { base.has_field.set_field (0, true); _clubid = value; }
			}
			public bool HasClubid {
				get { return base.has_field.has_field (0); }
			}

			private List<club_memberinfo> _members; // tag 1
			public List<club_memberinfo> members {
				get { return _members; }
				set { base.has_field.set_field (1, true); _members = value; }
			}
			public bool HasMembers {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubid = base.deserialize.read_integer ();
						break;
					case 1:
						this.members = base.deserialize.read_obj_list<club_memberinfo> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.clubid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.members, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_club_newapply {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _clubid; // tag 0
			public Int64 clubid {
				get { return _clubid; }
				set { base.has_field.set_field (0, true); _clubid = value; }
			}
			public bool HasClubid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.clubid, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_club_quit {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _clubid; // tag 0
			public Int64 clubid {
				get { return _clubid; }
				set { base.has_field.set_field (0, true); _clubid = value; }
			}
			public bool HasClubid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.clubid, 0);
				}

				return base.serialize.close ();
			}
		}


	}


}

