// Generated by sprotodump. DO NOT EDIT!
// source: F:\new\unity\TEngine\Tools\sproto/../../Configs/Sproto/club_c2s.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace C2sSprotoType { 
	public class cs_club_create {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private string _name; // tag 0
			public string name {
				get { return _name; }
				set { base.has_field.set_field (0, true); _name = value; }
			}
			public bool HasName {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.name = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.name, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class cs_club_join {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _clubid; // tag 0
			public Int64 clubid {
				get { return _clubid; }
				set { base.has_field.set_field (0, true); _clubid = value; }
			}
			public bool HasClubid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.clubid, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class cs_club_process_apply {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Int64 _clubid; // tag 0
			public Int64 clubid {
				get { return _clubid; }
				set { base.has_field.set_field (0, true); _clubid = value; }
			}
			public bool HasClubid {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _targetid; // tag 1
			public Int64 targetid {
				get { return _targetid; }
				set { base.has_field.set_field (1, true); _targetid = value; }
			}
			public bool HasTargetid {
				get { return base.has_field.has_field (1); }
			}

			private bool _result; // tag 2
			public bool result {
				get { return _result; }
				set { base.has_field.set_field (2, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (2); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubid = base.deserialize.read_integer ();
						break;
					case 1:
						this.targetid = base.deserialize.read_integer ();
						break;
					case 2:
						this.result = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.clubid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.targetid, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_boolean (this.result, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class cs_club_quit {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _clubid; // tag 0
			public Int64 clubid {
				get { return _clubid; }
				set { base.has_field.set_field (0, true); _clubid = value; }
			}
			public bool HasClubid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.clubid, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class cs_club_require_apply_list {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _clubid; // tag 0
			public Int64 clubid {
				get { return _clubid; }
				set { base.has_field.set_field (0, true); _clubid = value; }
			}
			public bool HasClubid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.clubid, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class cs_club_require_members {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _clubid; // tag 0
			public Int64 clubid {
				get { return _clubid; }
				set { base.has_field.set_field (0, true); _clubid = value; }
			}
			public bool HasClubid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.clubid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.clubid, 0);
				}

				return base.serialize.close ();
			}
		}


	}


}

