// Generated by sprotodump. DO NOT EDIT!
// source: F:\new\unity\TEngine\Tools\sproto/../../Configs/Sproto/eliminate_c2s.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace C2sSprotoType { 
	public class cs_eliminate_exit {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _roomid; // tag 0
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (0, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (0); }
			}

			private bool _practice; // tag 1
			public bool practice {
				get { return _practice; }
				set { base.has_field.set_field (1, true); _practice = value; }
			}
			public bool HasPractice {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.roomid = base.deserialize.read_integer ();
						break;
					case 1:
						this.practice = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.roomid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_boolean (this.practice, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class cs_eliminate_practice {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


	}


	public class cs_eliminate_reconnect {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _roomid; // tag 0
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (0, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.roomid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.roomid, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class cs_eliminate_switch {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Pos _p1; // tag 0
			public Pos p1 {
				get { return _p1; }
				set { base.has_field.set_field (0, true); _p1 = value; }
			}
			public bool HasP1 {
				get { return base.has_field.has_field (0); }
			}

			private Pos _p2; // tag 1
			public Pos p2 {
				get { return _p2; }
				set { base.has_field.set_field (1, true); _p2 = value; }
			}
			public bool HasP2 {
				get { return base.has_field.has_field (1); }
			}

			private bool _practice; // tag 2
			public bool practice {
				get { return _practice; }
				set { base.has_field.set_field (2, true); _practice = value; }
			}
			public bool HasPractice {
				get { return base.has_field.has_field (2); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.p1 = base.deserialize.read_obj<Pos> ();
						break;
					case 1:
						this.p2 = base.deserialize.read_obj<Pos> ();
						break;
					case 2:
						this.practice = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.p1, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.p2, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_boolean (this.practice, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class cs_eliminate_use_skill {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Int64 _id; // tag 0
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (0, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (0); }
			}

			private Pos _pos; // tag 1
			public Pos pos {
				get { return _pos; }
				set { base.has_field.set_field (1, true); _pos = value; }
			}
			public bool HasPos {
				get { return base.has_field.has_field (1); }
			}

			private bool _practice; // tag 2
			public bool practice {
				get { return _practice; }
				set { base.has_field.set_field (2, true); _practice = value; }
			}
			public bool HasPractice {
				get { return base.has_field.has_field (2); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.id = base.deserialize.read_integer ();
						break;
					case 1:
						this.pos = base.deserialize.read_obj<Pos> ();
						break;
					case 2:
						this.practice = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.id, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.pos, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_boolean (this.practice, 2);
				}

				return base.serialize.close ();
			}
		}


	}


}

