// Generated by sprotodump. DO NOT EDIT!
// source: F:\new\unity\TEngine\Tools\sproto/../../Configs/Sproto/eliminate_s2c.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace S2cSprotoType { 
	public class Eliminate_NewBombs : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Pos _frompos; // tag 0
		public Pos frompos {
			get { return _frompos; }
			set { base.has_field.set_field (0, true); _frompos = value; }
		}
		public bool HasFrompos {
			get { return base.has_field.has_field (0); }
		}

		private Pos _topos; // tag 1
		public Pos topos {
			get { return _topos; }
			set { base.has_field.set_field (1, true); _topos = value; }
		}
		public bool HasTopos {
			get { return base.has_field.has_field (1); }
		}

		public Eliminate_NewBombs () : base(max_field_count) {}

		public Eliminate_NewBombs (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.frompos = base.deserialize.read_obj<Pos> ();
					break;
				case 1:
					this.topos = base.deserialize.read_obj<Pos> ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_obj (this.frompos, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_obj (this.topos, 1);
			}

			return base.serialize.close ();
		}
	}


	public class Eliminate_Pair : SprotoTypeBase {
		private static int max_field_count = 7;
		
		
		private List<Eliminate_PairTile> _pos; // tag 0
		public List<Eliminate_PairTile> pos {
			get { return _pos; }
			set { base.has_field.set_field (0, true); _pos = value; }
		}
		public bool HasPos {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _bomb; // tag 1
		public Int64 bomb {
			get { return _bomb; }
			set { base.has_field.set_field (1, true); _bomb = value; }
		}
		public bool HasBomb {
			get { return base.has_field.has_field (1); }
		}

		private Pos _bombpos; // tag 2
		public Pos bombpos {
			get { return _bombpos; }
			set { base.has_field.set_field (2, true); _bombpos = value; }
		}
		public bool HasBombpos {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _batch; // tag 3
		public Int64 batch {
			get { return _batch; }
			set { base.has_field.set_field (3, true); _batch = value; }
		}
		public bool HasBatch {
			get { return base.has_field.has_field (3); }
		}

		private bool _addop; // tag 4
		public bool addop {
			get { return _addop; }
			set { base.has_field.set_field (4, true); _addop = value; }
		}
		public bool HasAddop {
			get { return base.has_field.has_field (4); }
		}

		private Pos _newbombpos; // tag 5
		public Pos newbombpos {
			get { return _newbombpos; }
			set { base.has_field.set_field (5, true); _newbombpos = value; }
		}
		public bool HasNewbombpos {
			get { return base.has_field.has_field (5); }
		}

		private Int64 _newbomb; // tag 6
		public Int64 newbomb {
			get { return _newbomb; }
			set { base.has_field.set_field (6, true); _newbomb = value; }
		}
		public bool HasNewbomb {
			get { return base.has_field.has_field (6); }
		}

		public Eliminate_Pair () : base(max_field_count) {}

		public Eliminate_Pair (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.pos = base.deserialize.read_obj_list<Eliminate_PairTile> ();
					break;
				case 1:
					this.bomb = base.deserialize.read_integer ();
					break;
				case 2:
					this.bombpos = base.deserialize.read_obj<Pos> ();
					break;
				case 3:
					this.batch = base.deserialize.read_integer ();
					break;
				case 4:
					this.addop = base.deserialize.read_boolean ();
					break;
				case 5:
					this.newbombpos = base.deserialize.read_obj<Pos> ();
					break;
				case 6:
					this.newbomb = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_obj (this.pos, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.bomb, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_obj (this.bombpos, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.batch, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_boolean (this.addop, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_obj (this.newbombpos, 5);
			}

			if (base.has_field.has_field (6)) {
				base.serialize.write_integer (this.newbomb, 6);
			}

			return base.serialize.close ();
		}
	}


	public class Eliminate_PairTile : SprotoTypeBase {
		private static int max_field_count = 4;
		
		
		private Int64 _x; // tag 0
		public Int64 x {
			get { return _x; }
			set { base.has_field.set_field (0, true); _x = value; }
		}
		public bool HasX {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _y; // tag 1
		public Int64 y {
			get { return _y; }
			set { base.has_field.set_field (1, true); _y = value; }
		}
		public bool HasY {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _tile; // tag 2
		public Int64 tile {
			get { return _tile; }
			set { base.has_field.set_field (2, true); _tile = value; }
		}
		public bool HasTile {
			get { return base.has_field.has_field (2); }
		}

		private bool _multi; // tag 3
		public bool multi {
			get { return _multi; }
			set { base.has_field.set_field (3, true); _multi = value; }
		}
		public bool HasMulti {
			get { return base.has_field.has_field (3); }
		}

		public Eliminate_PairTile () : base(max_field_count) {}

		public Eliminate_PairTile (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.x = base.deserialize.read_integer ();
					break;
				case 1:
					this.y = base.deserialize.read_integer ();
					break;
				case 2:
					this.tile = base.deserialize.read_integer ();
					break;
				case 3:
					this.multi = base.deserialize.read_boolean ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.x, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.y, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.tile, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_boolean (this.multi, 3);
			}

			return base.serialize.close ();
		}
	}


	public class Eliminate_Step : SprotoTypeBase {
		private static int max_field_count = 7;
		
		
		private List<Eliminate_Pair> _pair; // tag 0
		public List<Eliminate_Pair> pair {
			get { return _pair; }
			set { base.has_field.set_field (0, true); _pair = value; }
		}
		public bool HasPair {
			get { return base.has_field.has_field (0); }
		}

		private List<Eliminate_Tile> _map; // tag 1
		public List<Eliminate_Tile> map {
			get { return _map; }
			set { base.has_field.set_field (1, true); _map = value; }
		}
		public bool HasMap {
			get { return base.has_field.has_field (1); }
		}

		private List<Eliminate_NewBombs> _newbombs; // tag 2
		public List<Eliminate_NewBombs> newbombs {
			get { return _newbombs; }
			set { base.has_field.set_field (2, true); _newbombs = value; }
		}
		public bool HasNewbombs {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _score; // tag 3
		public Int64 score {
			get { return _score; }
			set { base.has_field.set_field (3, true); _score = value; }
		}
		public bool HasScore {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _add_score; // tag 4
		public Int64 add_score {
			get { return _add_score; }
			set { base.has_field.set_field (4, true); _add_score = value; }
		}
		public bool HasAdd_score {
			get { return base.has_field.has_field (4); }
		}

		private bool _dead; // tag 5
		public bool dead {
			get { return _dead; }
			set { base.has_field.set_field (5, true); _dead = value; }
		}
		public bool HasDead {
			get { return base.has_field.has_field (5); }
		}

		private Int64 _addopIdx; // tag 6
		public Int64 addopIdx {
			get { return _addopIdx; }
			set { base.has_field.set_field (6, true); _addopIdx = value; }
		}
		public bool HasAddopIdx {
			get { return base.has_field.has_field (6); }
		}

		public Eliminate_Step () : base(max_field_count) {}

		public Eliminate_Step (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.pair = base.deserialize.read_obj_list<Eliminate_Pair> ();
					break;
				case 1:
					this.map = base.deserialize.read_obj_list<Eliminate_Tile> ();
					break;
				case 2:
					this.newbombs = base.deserialize.read_obj_list<Eliminate_NewBombs> ();
					break;
				case 3:
					this.score = base.deserialize.read_integer ();
					break;
				case 4:
					this.add_score = base.deserialize.read_integer ();
					break;
				case 5:
					this.dead = base.deserialize.read_boolean ();
					break;
				case 6:
					this.addopIdx = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_obj (this.pair, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_obj (this.map, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_obj (this.newbombs, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.score, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.add_score, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_boolean (this.dead, 5);
			}

			if (base.has_field.has_field (6)) {
				base.serialize.write_integer (this.addopIdx, 6);
			}

			return base.serialize.close ();
		}
	}


	public class Eliminate_Tile : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _tile; // tag 0
		public Int64 tile {
			get { return _tile; }
			set { base.has_field.set_field (0, true); _tile = value; }
		}
		public bool HasTile {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _bomb; // tag 1
		public Int64 bomb {
			get { return _bomb; }
			set { base.has_field.set_field (1, true); _bomb = value; }
		}
		public bool HasBomb {
			get { return base.has_field.has_field (1); }
		}

		public Eliminate_Tile () : base(max_field_count) {}

		public Eliminate_Tile (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.tile = base.deserialize.read_integer ();
					break;
				case 1:
					this.bomb = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.tile, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.bomb, 1);
			}

			return base.serialize.close ();
		}
	}


	public class eliminate_member_info : SprotoTypeBase {
		private static int max_field_count = 6;
		
		
		private Int64 _dbid; // tag 0
		public Int64 dbid {
			get { return _dbid; }
			set { base.has_field.set_field (0, true); _dbid = value; }
		}
		public bool HasDbid {
			get { return base.has_field.has_field (0); }
		}

		private string _name; // tag 1
		public string name {
			get { return _name; }
			set { base.has_field.set_field (1, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (1); }
		}

		private string _head; // tag 2
		public string head {
			get { return _head; }
			set { base.has_field.set_field (2, true); _head = value; }
		}
		public bool HasHead {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _score; // tag 3
		public Int64 score {
			get { return _score; }
			set { base.has_field.set_field (3, true); _score = value; }
		}
		public bool HasScore {
			get { return base.has_field.has_field (3); }
		}

		private List<Int64> _skillcount; // tag 4
		public List<Int64> skillcount {
			get { return _skillcount; }
			set { base.has_field.set_field (4, true); _skillcount = value; }
		}
		public bool HasSkillcount {
			get { return base.has_field.has_field (4); }
		}

		private bool _quit; // tag 5
		public bool quit {
			get { return _quit; }
			set { base.has_field.set_field (5, true); _quit = value; }
		}
		public bool HasQuit {
			get { return base.has_field.has_field (5); }
		}

		public eliminate_member_info () : base(max_field_count) {}

		public eliminate_member_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.dbid = base.deserialize.read_integer ();
					break;
				case 1:
					this.name = base.deserialize.read_string ();
					break;
				case 2:
					this.head = base.deserialize.read_string ();
					break;
				case 3:
					this.score = base.deserialize.read_integer ();
					break;
				case 4:
					this.skillcount = base.deserialize.read_integer_list ();
					break;
				case 5:
					this.quit = base.deserialize.read_boolean ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.dbid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.name, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_string (this.head, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.score, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.skillcount, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_boolean (this.quit, 5);
			}

			return base.serialize.close ();
		}
	}


	public class eliminate_result_player : SprotoTypeBase {
		private static int max_field_count = 5;
		
		
		private Int64 _dbid; // tag 0
		public Int64 dbid {
			get { return _dbid; }
			set { base.has_field.set_field (0, true); _dbid = value; }
		}
		public bool HasDbid {
			get { return base.has_field.has_field (0); }
		}

		private string _name; // tag 1
		public string name {
			get { return _name; }
			set { base.has_field.set_field (1, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (1); }
		}

		private string _head; // tag 2
		public string head {
			get { return _head; }
			set { base.has_field.set_field (2, true); _head = value; }
		}
		public bool HasHead {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _score; // tag 3
		public Int64 score {
			get { return _score; }
			set { base.has_field.set_field (3, true); _score = value; }
		}
		public bool HasScore {
			get { return base.has_field.has_field (3); }
		}

		private bool _leave; // tag 4
		public bool leave {
			get { return _leave; }
			set { base.has_field.set_field (4, true); _leave = value; }
		}
		public bool HasLeave {
			get { return base.has_field.has_field (4); }
		}

		public eliminate_result_player () : base(max_field_count) {}

		public eliminate_result_player (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.dbid = base.deserialize.read_integer ();
					break;
				case 1:
					this.name = base.deserialize.read_string ();
					break;
				case 2:
					this.head = base.deserialize.read_string ();
					break;
				case 3:
					this.score = base.deserialize.read_integer ();
					break;
				case 4:
					this.leave = base.deserialize.read_boolean ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.dbid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.name, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_string (this.head, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.score, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_boolean (this.leave, 4);
			}

			return base.serialize.close ();
		}
	}


	public class sc_eliminate_finish {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 5;
			
			
			private Int64 _roomid; // tag 0
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (0, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _winner; // tag 1
			public Int64 winner {
				get { return _winner; }
				set { base.has_field.set_field (1, true); _winner = value; }
			}
			public bool HasWinner {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _reward; // tag 2
			public Int64 reward {
				get { return _reward; }
				set { base.has_field.set_field (2, true); _reward = value; }
			}
			public bool HasReward {
				get { return base.has_field.has_field (2); }
			}

			private List<eliminate_result_player> _result; // tag 3
			public List<eliminate_result_player> result {
				get { return _result; }
				set { base.has_field.set_field (3, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _fee; // tag 4
			public Int64 fee {
				get { return _fee; }
				set { base.has_field.set_field (4, true); _fee = value; }
			}
			public bool HasFee {
				get { return base.has_field.has_field (4); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.roomid = base.deserialize.read_integer ();
						break;
					case 1:
						this.winner = base.deserialize.read_integer ();
						break;
					case 2:
						this.reward = base.deserialize.read_integer ();
						break;
					case 3:
						this.result = base.deserialize.read_obj_list<eliminate_result_player> ();
						break;
					case 4:
						this.fee = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.roomid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.winner, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.reward, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_obj (this.result, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.fee, 4);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_game_reconnected {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 9;
			
			
			private List<Eliminate_Tile> _map; // tag 0
			public List<Eliminate_Tile> map {
				get { return _map; }
				set { base.has_field.set_field (0, true); _map = value; }
			}
			public bool HasMap {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _reward; // tag 1
			public Int64 reward {
				get { return _reward; }
				set { base.has_field.set_field (1, true); _reward = value; }
			}
			public bool HasReward {
				get { return base.has_field.has_field (1); }
			}

			private List<eliminate_member_info> _members; // tag 2
			public List<eliminate_member_info> members {
				get { return _members; }
				set { base.has_field.set_field (2, true); _members = value; }
			}
			public bool HasMembers {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _roomid; // tag 3
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (3, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _round; // tag 4
			public Int64 round {
				get { return _round; }
				set { base.has_field.set_field (4, true); _round = value; }
			}
			public bool HasRound {
				get { return base.has_field.has_field (4); }
			}

			private Int64 _playeridx; // tag 5
			public Int64 playeridx {
				get { return _playeridx; }
				set { base.has_field.set_field (5, true); _playeridx = value; }
			}
			public bool HasPlayeridx {
				get { return base.has_field.has_field (5); }
			}

			private Int64 _time; // tag 6
			public Int64 time {
				get { return _time; }
				set { base.has_field.set_field (6, true); _time = value; }
			}
			public bool HasTime {
				get { return base.has_field.has_field (6); }
			}

			private Int64 _opCount; // tag 7
			public Int64 opCount {
				get { return _opCount; }
				set { base.has_field.set_field (7, true); _opCount = value; }
			}
			public bool HasOpCount {
				get { return base.has_field.has_field (7); }
			}

			private List<Int64> _matchPlayers; // tag 8
			public List<Int64> matchPlayers {
				get { return _matchPlayers; }
				set { base.has_field.set_field (8, true); _matchPlayers = value; }
			}
			public bool HasMatchPlayers {
				get { return base.has_field.has_field (8); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.map = base.deserialize.read_obj_list<Eliminate_Tile> ();
						break;
					case 1:
						this.reward = base.deserialize.read_integer ();
						break;
					case 2:
						this.members = base.deserialize.read_obj_list<eliminate_member_info> ();
						break;
					case 3:
						this.roomid = base.deserialize.read_integer ();
						break;
					case 4:
						this.round = base.deserialize.read_integer ();
						break;
					case 5:
						this.playeridx = base.deserialize.read_integer ();
						break;
					case 6:
						this.time = base.deserialize.read_integer ();
						break;
					case 7:
						this.opCount = base.deserialize.read_integer ();
						break;
					case 8:
						this.matchPlayers = base.deserialize.read_integer_list ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.map, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.reward, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_obj (this.members, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.roomid, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.round, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_integer (this.playeridx, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_integer (this.time, 6);
				}

				if (base.has_field.has_field (7)) {
					base.serialize.write_integer (this.opCount, 7);
				}

				if (base.has_field.has_field (8)) {
					base.serialize.write_integer (this.matchPlayers, 8);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_map_info {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private List<Eliminate_Tile> _map; // tag 0
			public List<Eliminate_Tile> map {
				get { return _map; }
				set { base.has_field.set_field (0, true); _map = value; }
			}
			public bool HasMap {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _reward; // tag 1
			public Int64 reward {
				get { return _reward; }
				set { base.has_field.set_field (1, true); _reward = value; }
			}
			public bool HasReward {
				get { return base.has_field.has_field (1); }
			}

			private List<eliminate_member_info> _members; // tag 2
			public List<eliminate_member_info> members {
				get { return _members; }
				set { base.has_field.set_field (2, true); _members = value; }
			}
			public bool HasMembers {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _roomid; // tag 3
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (3, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (3); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.map = base.deserialize.read_obj_list<Eliminate_Tile> ();
						break;
					case 1:
						this.reward = base.deserialize.read_integer ();
						break;
					case 2:
						this.members = base.deserialize.read_obj_list<eliminate_member_info> ();
						break;
					case 3:
						this.roomid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.map, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.reward, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_obj (this.members, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.roomid, 3);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_map_start {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 8;
			
			
			private List<Eliminate_Tile> _map; // tag 0
			public List<Eliminate_Tile> map {
				get { return _map; }
				set { base.has_field.set_field (0, true); _map = value; }
			}
			public bool HasMap {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _reward; // tag 1
			public Int64 reward {
				get { return _reward; }
				set { base.has_field.set_field (1, true); _reward = value; }
			}
			public bool HasReward {
				get { return base.has_field.has_field (1); }
			}

			private List<eliminate_member_info> _members; // tag 2
			public List<eliminate_member_info> members {
				get { return _members; }
				set { base.has_field.set_field (2, true); _members = value; }
			}
			public bool HasMembers {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _round; // tag 3
			public Int64 round {
				get { return _round; }
				set { base.has_field.set_field (3, true); _round = value; }
			}
			public bool HasRound {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _playeridx; // tag 4
			public Int64 playeridx {
				get { return _playeridx; }
				set { base.has_field.set_field (4, true); _playeridx = value; }
			}
			public bool HasPlayeridx {
				get { return base.has_field.has_field (4); }
			}

			private Int64 _time; // tag 5
			public Int64 time {
				get { return _time; }
				set { base.has_field.set_field (5, true); _time = value; }
			}
			public bool HasTime {
				get { return base.has_field.has_field (5); }
			}

			private Int64 _opCount; // tag 6
			public Int64 opCount {
				get { return _opCount; }
				set { base.has_field.set_field (6, true); _opCount = value; }
			}
			public bool HasOpCount {
				get { return base.has_field.has_field (6); }
			}

			private bool _practice; // tag 7
			public bool practice {
				get { return _practice; }
				set { base.has_field.set_field (7, true); _practice = value; }
			}
			public bool HasPractice {
				get { return base.has_field.has_field (7); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.map = base.deserialize.read_obj_list<Eliminate_Tile> ();
						break;
					case 1:
						this.reward = base.deserialize.read_integer ();
						break;
					case 2:
						this.members = base.deserialize.read_obj_list<eliminate_member_info> ();
						break;
					case 3:
						this.round = base.deserialize.read_integer ();
						break;
					case 4:
						this.playeridx = base.deserialize.read_integer ();
						break;
					case 5:
						this.time = base.deserialize.read_integer ();
						break;
					case 6:
						this.opCount = base.deserialize.read_integer ();
						break;
					case 7:
						this.practice = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.map, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.reward, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_obj (this.members, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.round, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.playeridx, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_integer (this.time, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_integer (this.opCount, 6);
				}

				if (base.has_field.has_field (7)) {
					base.serialize.write_boolean (this.practice, 7);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_op_ret {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Pos _p1; // tag 0
			public Pos p1 {
				get { return _p1; }
				set { base.has_field.set_field (0, true); _p1 = value; }
			}
			public bool HasP1 {
				get { return base.has_field.has_field (0); }
			}

			private Pos _p2; // tag 1
			public Pos p2 {
				get { return _p2; }
				set { base.has_field.set_field (1, true); _p2 = value; }
			}
			public bool HasP2 {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _ret; // tag 2
			public Int64 ret {
				get { return _ret; }
				set { base.has_field.set_field (2, true); _ret = value; }
			}
			public bool HasRet {
				get { return base.has_field.has_field (2); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.p1 = base.deserialize.read_obj<Pos> ();
						break;
					case 1:
						this.p2 = base.deserialize.read_obj<Pos> ();
						break;
					case 2:
						this.ret = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.p1, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.p2, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.ret, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_op_step {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 9;
			
			
			private Pos _p1; // tag 0
			public Pos p1 {
				get { return _p1; }
				set { base.has_field.set_field (0, true); _p1 = value; }
			}
			public bool HasP1 {
				get { return base.has_field.has_field (0); }
			}

			private Pos _p2; // tag 1
			public Pos p2 {
				get { return _p2; }
				set { base.has_field.set_field (1, true); _p2 = value; }
			}
			public bool HasP2 {
				get { return base.has_field.has_field (1); }
			}

			private List<Eliminate_Step> _step; // tag 2
			public List<Eliminate_Step> step {
				get { return _step; }
				set { base.has_field.set_field (2, true); _step = value; }
			}
			public bool HasStep {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _dbid; // tag 3
			public Int64 dbid {
				get { return _dbid; }
				set { base.has_field.set_field (3, true); _dbid = value; }
			}
			public bool HasDbid {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _opCount; // tag 4
			public Int64 opCount {
				get { return _opCount; }
				set { base.has_field.set_field (4, true); _opCount = value; }
			}
			public bool HasOpCount {
				get { return base.has_field.has_field (4); }
			}

			private Int64 _roundTime; // tag 7
			public Int64 roundTime {
				get { return _roundTime; }
				set { base.has_field.set_field (5, true); _roundTime = value; }
			}
			public bool HasRoundTime {
				get { return base.has_field.has_field (5); }
			}

			private Int64 _changeOpCount; // tag 8
			public Int64 changeOpCount {
				get { return _changeOpCount; }
				set { base.has_field.set_field (6, true); _changeOpCount = value; }
			}
			public bool HasChangeOpCount {
				get { return base.has_field.has_field (6); }
			}

			private bool _crossbomb; // tag 9
			public bool crossbomb {
				get { return _crossbomb; }
				set { base.has_field.set_field (7, true); _crossbomb = value; }
			}
			public bool HasCrossbomb {
				get { return base.has_field.has_field (7); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.p1 = base.deserialize.read_obj<Pos> ();
						break;
					case 1:
						this.p2 = base.deserialize.read_obj<Pos> ();
						break;
					case 2:
						this.step = base.deserialize.read_obj_list<Eliminate_Step> ();
						break;
					case 3:
						this.dbid = base.deserialize.read_integer ();
						break;
					case 4:
						this.opCount = base.deserialize.read_integer ();
						break;
					case 7:
						this.roundTime = base.deserialize.read_integer ();
						break;
					case 8:
						this.changeOpCount = base.deserialize.read_integer ();
						break;
					case 9:
						this.crossbomb = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.p1, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.p2, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_obj (this.step, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.dbid, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.opCount, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_integer (this.roundTime, 7);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_integer (this.changeOpCount, 8);
				}

				if (base.has_field.has_field (7)) {
					base.serialize.write_boolean (this.crossbomb, 9);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_otherplayerExit {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 7;
			
			
			private Int64 _roomid; // tag 0
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (0, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _dbid; // tag 1
			public Int64 dbid {
				get { return _dbid; }
				set { base.has_field.set_field (1, true); _dbid = value; }
			}
			public bool HasDbid {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _playeridx; // tag 2
			public Int64 playeridx {
				get { return _playeridx; }
				set { base.has_field.set_field (2, true); _playeridx = value; }
			}
			public bool HasPlayeridx {
				get { return base.has_field.has_field (2); }
			}

			private List<Int64> _matchPlayers; // tag 3
			public List<Int64> matchPlayers {
				get { return _matchPlayers; }
				set { base.has_field.set_field (3, true); _matchPlayers = value; }
			}
			public bool HasMatchPlayers {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _round; // tag 4
			public Int64 round {
				get { return _round; }
				set { base.has_field.set_field (4, true); _round = value; }
			}
			public bool HasRound {
				get { return base.has_field.has_field (4); }
			}

			private Int64 _time; // tag 5
			public Int64 time {
				get { return _time; }
				set { base.has_field.set_field (5, true); _time = value; }
			}
			public bool HasTime {
				get { return base.has_field.has_field (5); }
			}

			private Int64 _opCount; // tag 6
			public Int64 opCount {
				get { return _opCount; }
				set { base.has_field.set_field (6, true); _opCount = value; }
			}
			public bool HasOpCount {
				get { return base.has_field.has_field (6); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.roomid = base.deserialize.read_integer ();
						break;
					case 1:
						this.dbid = base.deserialize.read_integer ();
						break;
					case 2:
						this.playeridx = base.deserialize.read_integer ();
						break;
					case 3:
						this.matchPlayers = base.deserialize.read_integer_list ();
						break;
					case 4:
						this.round = base.deserialize.read_integer ();
						break;
					case 5:
						this.time = base.deserialize.read_integer ();
						break;
					case 6:
						this.opCount = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.roomid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.dbid, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.playeridx, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.matchPlayers, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.round, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_integer (this.time, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_integer (this.opCount, 6);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_playerExit {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _roomid; // tag 0
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (0, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.roomid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.roomid, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_reconnect {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _roomid; // tag 0
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (0, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.roomid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.roomid, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_round_info {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 5;
			
			
			private Int64 _round; // tag 0
			public Int64 round {
				get { return _round; }
				set { base.has_field.set_field (0, true); _round = value; }
			}
			public bool HasRound {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _playeridx; // tag 1
			public Int64 playeridx {
				get { return _playeridx; }
				set { base.has_field.set_field (1, true); _playeridx = value; }
			}
			public bool HasPlayeridx {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _time; // tag 2
			public Int64 time {
				get { return _time; }
				set { base.has_field.set_field (2, true); _time = value; }
			}
			public bool HasTime {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _opCount; // tag 3
			public Int64 opCount {
				get { return _opCount; }
				set { base.has_field.set_field (3, true); _opCount = value; }
			}
			public bool HasOpCount {
				get { return base.has_field.has_field (3); }
			}

			private List<Int64> _matchPlayers; // tag 4
			public List<Int64> matchPlayers {
				get { return _matchPlayers; }
				set { base.has_field.set_field (4, true); _matchPlayers = value; }
			}
			public bool HasMatchPlayers {
				get { return base.has_field.has_field (4); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.round = base.deserialize.read_integer ();
						break;
					case 1:
						this.playeridx = base.deserialize.read_integer ();
						break;
					case 2:
						this.time = base.deserialize.read_integer ();
						break;
					case 3:
						this.opCount = base.deserialize.read_integer ();
						break;
					case 4:
						this.matchPlayers = base.deserialize.read_integer_list ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.round, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.playeridx, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.time, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.opCount, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.matchPlayers, 4);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_useskill_ret {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _ret; // tag 0
			public Int64 ret {
				get { return _ret; }
				set { base.has_field.set_field (0, true); _ret = value; }
			}
			public bool HasRet {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.ret = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.ret, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_eliminate_useskill_step {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 8;
			
			
			private Pos _pos; // tag 0
			public Pos pos {
				get { return _pos; }
				set { base.has_field.set_field (0, true); _pos = value; }
			}
			public bool HasPos {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _skillid; // tag 1
			public Int64 skillid {
				get { return _skillid; }
				set { base.has_field.set_field (1, true); _skillid = value; }
			}
			public bool HasSkillid {
				get { return base.has_field.has_field (1); }
			}

			private List<Eliminate_Step> _step; // tag 2
			public List<Eliminate_Step> step {
				get { return _step; }
				set { base.has_field.set_field (2, true); _step = value; }
			}
			public bool HasStep {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _dbid; // tag 3
			public Int64 dbid {
				get { return _dbid; }
				set { base.has_field.set_field (3, true); _dbid = value; }
			}
			public bool HasDbid {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _opCount; // tag 4
			public Int64 opCount {
				get { return _opCount; }
				set { base.has_field.set_field (4, true); _opCount = value; }
			}
			public bool HasOpCount {
				get { return base.has_field.has_field (4); }
			}

			private List<Int64> _skillcount; // tag 5
			public List<Int64> skillcount {
				get { return _skillcount; }
				set { base.has_field.set_field (5, true); _skillcount = value; }
			}
			public bool HasSkillcount {
				get { return base.has_field.has_field (5); }
			}

			private List<Eliminate_Tile> _map; // tag 6
			public List<Eliminate_Tile> map {
				get { return _map; }
				set { base.has_field.set_field (6, true); _map = value; }
			}
			public bool HasMap {
				get { return base.has_field.has_field (6); }
			}

			private Int64 _roundTime; // tag 7
			public Int64 roundTime {
				get { return _roundTime; }
				set { base.has_field.set_field (7, true); _roundTime = value; }
			}
			public bool HasRoundTime {
				get { return base.has_field.has_field (7); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.pos = base.deserialize.read_obj<Pos> ();
						break;
					case 1:
						this.skillid = base.deserialize.read_integer ();
						break;
					case 2:
						this.step = base.deserialize.read_obj_list<Eliminate_Step> ();
						break;
					case 3:
						this.dbid = base.deserialize.read_integer ();
						break;
					case 4:
						this.opCount = base.deserialize.read_integer ();
						break;
					case 5:
						this.skillcount = base.deserialize.read_integer_list ();
						break;
					case 6:
						this.map = base.deserialize.read_obj_list<Eliminate_Tile> ();
						break;
					case 7:
						this.roundTime = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.pos, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.skillid, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_obj (this.step, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.dbid, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.opCount, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_integer (this.skillcount, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_obj (this.map, 6);
				}

				if (base.has_field.has_field (7)) {
					base.serialize.write_integer (this.roundTime, 7);
				}

				return base.serialize.close ();
			}
		}


	}


}

