// Generated by sprotodump. DO NOT EDIT!
// source: F:\new\unity\TEngine\Tools\sproto/../../Configs/Sproto/gamec2s.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace C2sSprotoType { 
	public class ActorCount {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private string _account; // tag 0
			public string account {
				get { return _account; }
				set { base.has_field.set_field (0, true); _account = value; }
			}
			public bool HasAccount {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _serverid; // tag 1
			public Int64 serverid {
				get { return _serverid; }
				set { base.has_field.set_field (1, true); _serverid = value; }
			}
			public bool HasServerid {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.account = base.deserialize.read_string ();
						break;
					case 1:
						this.serverid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.account, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.serverid, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _actorcount; // tag 0
			public Int64 actorcount {
				get { return _actorcount; }
				set { base.has_field.set_field (0, true); _actorcount = value; }
			}
			public bool HasActorcount {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.actorcount = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.actorcount, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class CreateActor {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 7;
			
			
			private string _actorname; // tag 0
			public string actorname {
				get { return _actorname; }
				set { base.has_field.set_field (0, true); _actorname = value; }
			}
			public bool HasActorname {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _sex; // tag 1
			public Int64 sex {
				get { return _sex; }
				set { base.has_field.set_field (1, true); _sex = value; }
			}
			public bool HasSex {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _job; // tag 2
			public Int64 job {
				get { return _job; }
				set { base.has_field.set_field (2, true); _job = value; }
			}
			public bool HasJob {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _icon; // tag 3
			public Int64 icon {
				get { return _icon; }
				set { base.has_field.set_field (3, true); _icon = value; }
			}
			public bool HasIcon {
				get { return base.has_field.has_field (3); }
			}

			private string _pf; // tag 4
			public string pf {
				get { return _pf; }
				set { base.has_field.set_field (4, true); _pf = value; }
			}
			public bool HasPf {
				get { return base.has_field.has_field (4); }
			}

			private string _account; // tag 5
			public string account {
				get { return _account; }
				set { base.has_field.set_field (5, true); _account = value; }
			}
			public bool HasAccount {
				get { return base.has_field.has_field (5); }
			}

			private bool _randname; // tag 6
			public bool randname {
				get { return _randname; }
				set { base.has_field.set_field (6, true); _randname = value; }
			}
			public bool HasRandname {
				get { return base.has_field.has_field (6); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.actorname = base.deserialize.read_string ();
						break;
					case 1:
						this.sex = base.deserialize.read_integer ();
						break;
					case 2:
						this.job = base.deserialize.read_integer ();
						break;
					case 3:
						this.icon = base.deserialize.read_integer ();
						break;
					case 4:
						this.pf = base.deserialize.read_string ();
						break;
					case 5:
						this.account = base.deserialize.read_string ();
						break;
					case 6:
						this.randname = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.actorname, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.sex, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.job, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.icon, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_string (this.pf, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_string (this.account, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_boolean (this.randname, 6);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _actorid; // tag 1
			public Int64 actorid {
				get { return _actorid; }
				set { base.has_field.set_field (1, true); _actorid = value; }
			}
			public bool HasActorid {
				get { return base.has_field.has_field (1); }
			}

			private string _name; // tag 2
			public string name {
				get { return _name; }
				set { base.has_field.set_field (2, true); _name = value; }
			}
			public bool HasName {
				get { return base.has_field.has_field (2); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					case 1:
						this.actorid = base.deserialize.read_integer ();
						break;
					case 2:
						this.name = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.actorid, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_string (this.name, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class DelayActorCreate {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private string _actorname; // tag 0
			public string actorname {
				get { return _actorname; }
				set { base.has_field.set_field (0, true); _actorname = value; }
			}
			public bool HasActorname {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _sex; // tag 1
			public Int64 sex {
				get { return _sex; }
				set { base.has_field.set_field (1, true); _sex = value; }
			}
			public bool HasSex {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _job; // tag 2
			public Int64 job {
				get { return _job; }
				set { base.has_field.set_field (2, true); _job = value; }
			}
			public bool HasJob {
				get { return base.has_field.has_field (2); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.actorname = base.deserialize.read_string ();
						break;
					case 1:
						this.sex = base.deserialize.read_integer ();
						break;
					case 2:
						this.job = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.actorname, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.sex, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.job, 2);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			private string _name; // tag 1
			public string name {
				get { return _name; }
				set { base.has_field.set_field (1, true); _name = value; }
			}
			public bool HasName {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _sex; // tag 2
			public Int64 sex {
				get { return _sex; }
				set { base.has_field.set_field (2, true); _sex = value; }
			}
			public bool HasSex {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _job; // tag 3
			public Int64 job {
				get { return _job; }
				set { base.has_field.set_field (3, true); _job = value; }
			}
			public bool HasJob {
				get { return base.has_field.has_field (3); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					case 1:
						this.name = base.deserialize.read_string ();
						break;
					case 2:
						this.sex = base.deserialize.read_integer ();
						break;
					case 3:
						this.job = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.name, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.sex, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.job, 3);
				}

				return base.serialize.close ();
			}
		}


	}


	public class EnterGame {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _actorid; // tag 0
			public Int64 actorid {
				get { return _actorid; }
				set { base.has_field.set_field (0, true); _actorid = value; }
			}
			public bool HasActorid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.actorid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.actorid, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			private string _QQ; // tag 1
			public string QQ {
				get { return _QQ; }
				set { base.has_field.set_field (1, true); _QQ = value; }
			}
			public bool HasQQ {
				get { return base.has_field.has_field (1); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					case 1:
						this.QQ = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.QQ, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class LockName {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private string _actorname; // tag 0
			public string actorname {
				get { return _actorname; }
				set { base.has_field.set_field (0, true); _actorname = value; }
			}
			public bool HasActorname {
				get { return base.has_field.has_field (0); }
			}

			private string _account; // tag 1
			public string account {
				get { return _account; }
				set { base.has_field.set_field (1, true); _account = value; }
			}
			public bool HasAccount {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.actorname = base.deserialize.read_string ();
						break;
					case 1:
						this.account = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.actorname, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.account, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class QueryList {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private bool _code; // tag 0
			public bool code {
				get { return _code; }
				set { base.has_field.set_field (0, true); _code = value; }
			}
			public bool HasCode {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _actorid; // tag 1
			public Int64 actorid {
				get { return _actorid; }
				set { base.has_field.set_field (1, true); _actorid = value; }
			}
			public bool HasActorid {
				get { return base.has_field.has_field (1); }
			}

			private List<actorlist> _actorlist; // tag 2
			public List<actorlist> actorlist {
				get { return _actorlist; }
				set { base.has_field.set_field (2, true); _actorlist = value; }
			}
			public bool HasActorlist {
				get { return base.has_field.has_field (2); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.code = base.deserialize.read_boolean ();
						break;
					case 1:
						this.actorid = base.deserialize.read_integer ();
						break;
					case 2:
						this.actorlist = base.deserialize.read_obj_list<actorlist> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_boolean (this.code, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.actorid, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_obj (this.actorlist, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class RandName {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _sex; // tag 0
			public Int64 sex {
				get { return _sex; }
				set { base.has_field.set_field (0, true); _sex = value; }
			}
			public bool HasSex {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.sex = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.sex, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			private string _actorname; // tag 1
			public string actorname {
				get { return _actorname; }
				set { base.has_field.set_field (1, true); _actorname = value; }
			}
			public bool HasActorname {
				get { return base.has_field.has_field (1); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					case 1:
						this.actorname = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.actorname, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class Rename {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private string _actorname; // tag 0
			public string actorname {
				get { return _actorname; }
				set { base.has_field.set_field (0, true); _actorname = value; }
			}
			public bool HasActorname {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.actorname = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.actorname, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _ret; // tag 0
			public Int64 ret {
				get { return _ret; }
				set { base.has_field.set_field (0, true); _ret = value; }
			}
			public bool HasRet {
				get { return base.has_field.has_field (0); }
			}

			private string _name; // tag 1
			public string name {
				get { return _name; }
				set { base.has_field.set_field (1, true); _name = value; }
			}
			public bool HasName {
				get { return base.has_field.has_field (1); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.ret = base.deserialize.read_integer ();
						break;
					case 1:
						this.name = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.ret, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.name, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class actorlist : SprotoTypeBase {
		private static int max_field_count = 8;
		
		
		private Int64 _dbid; // tag 0
		public Int64 dbid {
			get { return _dbid; }
			set { base.has_field.set_field (0, true); _dbid = value; }
		}
		public bool HasDbid {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _serverindex; // tag 1
		public Int64 serverindex {
			get { return _serverindex; }
			set { base.has_field.set_field (1, true); _serverindex = value; }
		}
		public bool HasServerindex {
			get { return base.has_field.has_field (1); }
		}

		private string _actorname; // tag 2
		public string actorname {
			get { return _actorname; }
			set { base.has_field.set_field (2, true); _actorname = value; }
		}
		public bool HasActorname {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _job; // tag 3
		public Int64 job {
			get { return _job; }
			set { base.has_field.set_field (3, true); _job = value; }
		}
		public bool HasJob {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _sex; // tag 4
		public Int64 sex {
			get { return _sex; }
			set { base.has_field.set_field (4, true); _sex = value; }
		}
		public bool HasSex {
			get { return base.has_field.has_field (4); }
		}

		private Int64 _level; // tag 5
		public Int64 level {
			get { return _level; }
			set { base.has_field.set_field (5, true); _level = value; }
		}
		public bool HasLevel {
			get { return base.has_field.has_field (5); }
		}

		private Int64 _zhuansheng_lv; // tag 6
		public Int64 zhuansheng_lv {
			get { return _zhuansheng_lv; }
			set { base.has_field.set_field (6, true); _zhuansheng_lv = value; }
		}
		public bool HasZhuansheng_lv {
			get { return base.has_field.has_field (6); }
		}

		private Int64 _totalpower; // tag 7
		public Int64 totalpower {
			get { return _totalpower; }
			set { base.has_field.set_field (7, true); _totalpower = value; }
		}
		public bool HasTotalpower {
			get { return base.has_field.has_field (7); }
		}

		public actorlist () : base(max_field_count) {}

		public actorlist (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.dbid = base.deserialize.read_integer ();
					break;
				case 1:
					this.serverindex = base.deserialize.read_integer ();
					break;
				case 2:
					this.actorname = base.deserialize.read_string ();
					break;
				case 3:
					this.job = base.deserialize.read_integer ();
					break;
				case 4:
					this.sex = base.deserialize.read_integer ();
					break;
				case 5:
					this.level = base.deserialize.read_integer ();
					break;
				case 6:
					this.zhuansheng_lv = base.deserialize.read_integer ();
					break;
				case 7:
					this.totalpower = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.dbid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.serverindex, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_string (this.actorname, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.job, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.sex, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_integer (this.level, 5);
			}

			if (base.has_field.has_field (6)) {
				base.serialize.write_integer (this.zhuansheng_lv, 6);
			}

			if (base.has_field.has_field (7)) {
				base.serialize.write_integer (this.totalpower, 7);
			}

			return base.serialize.close ();
		}
	}


	public class checkAccount {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 11;
			
			
			private string _accountname; // tag 0
			public string accountname {
				get { return _accountname; }
				set { base.has_field.set_field (0, true); _accountname = value; }
			}
			public bool HasAccountname {
				get { return base.has_field.has_field (0); }
			}

			private string _password; // tag 1
			public string password {
				get { return _password; }
				set { base.has_field.set_field (1, true); _password = value; }
			}
			public bool HasPassword {
				get { return base.has_field.has_field (1); }
			}

			private string _platformuid; // tag 2
			public string platformuid {
				get { return _platformuid; }
				set { base.has_field.set_field (2, true); _platformuid = value; }
			}
			public bool HasPlatformuid {
				get { return base.has_field.has_field (2); }
			}

			private string _token; // tag 3
			public string token {
				get { return _token; }
				set { base.has_field.set_field (3, true); _token = value; }
			}
			public bool HasToken {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _serverid; // tag 4
			public Int64 serverid {
				get { return _serverid; }
				set { base.has_field.set_field (4, true); _serverid = value; }
			}
			public bool HasServerid {
				get { return base.has_field.has_field (4); }
			}

			private string _lid; // tag 5
			public string lid {
				get { return _lid; }
				set { base.has_field.set_field (5, true); _lid = value; }
			}
			public bool HasLid {
				get { return base.has_field.has_field (5); }
			}

			private Int64 _gameid; // tag 6
			public Int64 gameid {
				get { return _gameid; }
				set { base.has_field.set_field (6, true); _gameid = value; }
			}
			public bool HasGameid {
				get { return base.has_field.has_field (6); }
			}

			private Int64 _opid; // tag 7
			public Int64 opid {
				get { return _opid; }
				set { base.has_field.set_field (7, true); _opid = value; }
			}
			public bool HasOpid {
				get { return base.has_field.has_field (7); }
			}

			private string _shareQuery; // tag 8
			public string shareQuery {
				get { return _shareQuery; }
				set { base.has_field.set_field (8, true); _shareQuery = value; }
			}
			public bool HasShareQuery {
				get { return base.has_field.has_field (8); }
			}

			private Int64 _wxscene; // tag 9
			public Int64 wxscene {
				get { return _wxscene; }
				set { base.has_field.set_field (9, true); _wxscene = value; }
			}
			public bool HasWxscene {
				get { return base.has_field.has_field (9); }
			}

			private string _wxuserinfo; // tag 10
			public string wxuserinfo {
				get { return _wxuserinfo; }
				set { base.has_field.set_field (10, true); _wxuserinfo = value; }
			}
			public bool HasWxuserinfo {
				get { return base.has_field.has_field (10); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.accountname = base.deserialize.read_string ();
						break;
					case 1:
						this.password = base.deserialize.read_string ();
						break;
					case 2:
						this.platformuid = base.deserialize.read_string ();
						break;
					case 3:
						this.token = base.deserialize.read_string ();
						break;
					case 4:
						this.serverid = base.deserialize.read_integer ();
						break;
					case 5:
						this.lid = base.deserialize.read_string ();
						break;
					case 6:
						this.gameid = base.deserialize.read_integer ();
						break;
					case 7:
						this.opid = base.deserialize.read_integer ();
						break;
					case 8:
						this.shareQuery = base.deserialize.read_string ();
						break;
					case 9:
						this.wxscene = base.deserialize.read_integer ();
						break;
					case 10:
						this.wxuserinfo = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.accountname, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.password, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_string (this.platformuid, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_string (this.token, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.serverid, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_string (this.lid, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_integer (this.gameid, 6);
				}

				if (base.has_field.has_field (7)) {
					base.serialize.write_integer (this.opid, 7);
				}

				if (base.has_field.has_field (8)) {
					base.serialize.write_string (this.shareQuery, 8);
				}

				if (base.has_field.has_field (9)) {
					base.serialize.write_integer (this.wxscene, 9);
				}

				if (base.has_field.has_field (10)) {
					base.serialize.write_string (this.wxuserinfo, 10);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				return base.serialize.close ();
			}
		}


	}


}

