// Generated by sprotodump. DO NOT EDIT!
// source: F:\new\unity\TEngine\Tools\sproto/../../Configs/Sproto/games2c.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace S2cSprotoType { 
	public class sc_actor_eliminate_count_info {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _eliminatecount; // tag 0
			public Int64 eliminatecount {
				get { return _eliminatecount; }
				set { base.has_field.set_field (0, true); _eliminatecount = value; }
			}
			public bool HasEliminatecount {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _eliminatewinner; // tag 1
			public Int64 eliminatewinner {
				get { return _eliminatewinner; }
				set { base.has_field.set_field (1, true); _eliminatewinner = value; }
			}
			public bool HasEliminatewinner {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.eliminatecount = base.deserialize.read_integer ();
						break;
					case 1:
						this.eliminatewinner = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.eliminatecount, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.eliminatewinner, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_base_game_time {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Int64 _time; // tag 0
			public Int64 time {
				get { return _time; }
				set { base.has_field.set_field (0, true); _time = value; }
			}
			public bool HasTime {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _serverRunDay; // tag 1
			public Int64 serverRunDay {
				get { return _serverRunDay; }
				set { base.has_field.set_field (1, true); _serverRunDay = value; }
			}
			public bool HasServerRunDay {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _yearWeek; // tag 2
			public Int64 yearWeek {
				get { return _yearWeek; }
				set { base.has_field.set_field (2, true); _yearWeek = value; }
			}
			public bool HasYearWeek {
				get { return base.has_field.has_field (2); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.time = base.deserialize.read_integer ();
						break;
					case 1:
						this.serverRunDay = base.deserialize.read_integer ();
						break;
					case 2:
						this.yearWeek = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.time, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.serverRunDay, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.yearWeek, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_base_open_day {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 5;
			
			
			private Int64 _day; // tag 1
			public Int64 day {
				get { return _day; }
				set { base.has_field.set_field (0, true); _day = value; }
			}
			public bool HasDay {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _loginDay; // tag 2
			public Int64 loginDay {
				get { return _loginDay; }
				set { base.has_field.set_field (1, true); _loginDay = value; }
			}
			public bool HasLoginDay {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _mergeDay; // tag 3
			public Int64 mergeDay {
				get { return _mergeDay; }
				set { base.has_field.set_field (2, true); _mergeDay = value; }
			}
			public bool HasMergeDay {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _createDay; // tag 4
			public Int64 createDay {
				get { return _createDay; }
				set { base.has_field.set_field (3, true); _createDay = value; }
			}
			public bool HasCreateDay {
				get { return base.has_field.has_field (3); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 1:
						this.day = base.deserialize.read_integer ();
						break;
					case 2:
						this.loginDay = base.deserialize.read_integer ();
						break;
					case 3:
						this.mergeDay = base.deserialize.read_integer ();
						break;
					case 4:
						this.createDay = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.day, 1);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.loginDay, 2);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.mergeDay, 3);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.createDay, 4);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_check_account_result {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_coin_update {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _coin; // tag 0
			public Int64 coin {
				get { return _coin; }
				set { base.has_field.set_field (0, true); _coin = value; }
			}
			public bool HasCoin {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.coin = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.coin, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_enter_game {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 7;
			
			
			private bool _newPlayer; // tag 0
			public bool newPlayer {
				get { return _newPlayer; }
				set { base.has_field.set_field (0, true); _newPlayer = value; }
			}
			public bool HasNewPlayer {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _dbid; // tag 1
			public Int64 dbid {
				get { return _dbid; }
				set { base.has_field.set_field (1, true); _dbid = value; }
			}
			public bool HasDbid {
				get { return base.has_field.has_field (1); }
			}

			private string _name; // tag 2
			public string name {
				get { return _name; }
				set { base.has_field.set_field (2, true); _name = value; }
			}
			public bool HasName {
				get { return base.has_field.has_field (2); }
			}

			private string _head; // tag 3
			public string head {
				get { return _head; }
				set { base.has_field.set_field (3, true); _head = value; }
			}
			public bool HasHead {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _coin; // tag 4
			public Int64 coin {
				get { return _coin; }
				set { base.has_field.set_field (4, true); _coin = value; }
			}
			public bool HasCoin {
				get { return base.has_field.has_field (4); }
			}

			private Int64 _eliminatecount; // tag 5
			public Int64 eliminatecount {
				get { return _eliminatecount; }
				set { base.has_field.set_field (5, true); _eliminatecount = value; }
			}
			public bool HasEliminatecount {
				get { return base.has_field.has_field (5); }
			}

			private Int64 _eliminatewinner; // tag 6
			public Int64 eliminatewinner {
				get { return _eliminatewinner; }
				set { base.has_field.set_field (6, true); _eliminatewinner = value; }
			}
			public bool HasEliminatewinner {
				get { return base.has_field.has_field (6); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.newPlayer = base.deserialize.read_boolean ();
						break;
					case 1:
						this.dbid = base.deserialize.read_integer ();
						break;
					case 2:
						this.name = base.deserialize.read_string ();
						break;
					case 3:
						this.head = base.deserialize.read_string ();
						break;
					case 4:
						this.coin = base.deserialize.read_integer ();
						break;
					case 5:
						this.eliminatecount = base.deserialize.read_integer ();
						break;
					case 6:
						this.eliminatewinner = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_boolean (this.newPlayer, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.dbid, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_string (this.name, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_string (this.head, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.coin, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_integer (this.eliminatecount, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_integer (this.eliminatewinner, 6);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_error_code {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _code; // tag 0
			public Int64 code {
				get { return _code; }
				set { base.has_field.set_field (0, true); _code = value; }
			}
			public bool HasCode {
				get { return base.has_field.has_field (0); }
			}

			private string _msg; // tag 1
			public string msg {
				get { return _msg; }
				set { base.has_field.set_field (1, true); _msg = value; }
			}
			public bool HasMsg {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.code = base.deserialize.read_integer ();
						break;
					case 1:
						this.msg = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.code, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.msg, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_error_warninfo {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _code; // tag 0
			public Int64 code {
				get { return _code; }
				set { base.has_field.set_field (0, true); _code = value; }
			}
			public bool HasCode {
				get { return base.has_field.has_field (0); }
			}

			private string _msg; // tag 1
			public string msg {
				get { return _msg; }
				set { base.has_field.set_field (1, true); _msg = value; }
			}
			public bool HasMsg {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.code = base.deserialize.read_integer ();
						break;
					case 1:
						this.msg = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.code, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.msg, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_getcoin_recharge {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _coin; // tag 0
			public Int64 coin {
				get { return _coin; }
				set { base.has_field.set_field (0, true); _coin = value; }
			}
			public bool HasCoin {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.coin = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.coin, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_recharge_success {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _id; // tag 0
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (0, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _coin; // tag 1
			public Int64 coin {
				get { return _coin; }
				set { base.has_field.set_field (1, true); _coin = value; }
			}
			public bool HasCoin {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.id = base.deserialize.read_integer ();
						break;
					case 1:
						this.coin = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.id, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.coin, 1);
				}

				return base.serialize.close ();
			}
		}


	}


}

