// Generated by sprotodump. DO NOT EDIT!
// source: F:\new\unity\TEngine\Tools\sproto/../../Configs/Sproto/gameplays2c.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace S2cSprotoType { 
	public class gameplays2c_bagInfo {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<ItemDataStr> _list; // tag 0
			public List<ItemDataStr> list {
				get { return _list; }
				set { base.has_field.set_field (0, true); _list = value; }
			}
			public bool HasList {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.list = base.deserialize.read_obj_list<ItemDataStr> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.list, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_cashData {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private List<CashData> _records; // tag 0
			public List<CashData> records {
				get { return _records; }
				set { base.has_field.set_field (0, true); _records = value; }
			}
			public bool HasRecords {
				get { return base.has_field.has_field (0); }
			}

			private List<Int64> _hongbaos; // tag 1
			public List<Int64> hongbaos {
				get { return _hongbaos; }
				set { base.has_field.set_field (1, true); _hongbaos = value; }
			}
			public bool HasHongbaos {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _hongbaoCdTime; // tag 2
			public Int64 hongbaoCdTime {
				get { return _hongbaoCdTime; }
				set { base.has_field.set_field (2, true); _hongbaoCdTime = value; }
			}
			public bool HasHongbaoCdTime {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _hongbaoReduceCdTime; // tag 3
			public Int64 hongbaoReduceCdTime {
				get { return _hongbaoReduceCdTime; }
				set { base.has_field.set_field (3, true); _hongbaoReduceCdTime = value; }
			}
			public bool HasHongbaoReduceCdTime {
				get { return base.has_field.has_field (3); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.records = base.deserialize.read_obj_list<CashData> ();
						break;
					case 1:
						this.hongbaos = base.deserialize.read_integer_list ();
						break;
					case 2:
						this.hongbaoCdTime = base.deserialize.read_integer ();
						break;
					case 3:
						this.hongbaoReduceCdTime = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.records, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.hongbaos, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.hongbaoCdTime, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.hongbaoReduceCdTime, 3);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_finishTutorial {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _step; // tag 0
			public Int64 step {
				get { return _step; }
				set { base.has_field.set_field (0, true); _step = value; }
			}
			public bool HasStep {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.step = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.step, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_gradeInfo {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<GradeData> _grades; // tag 0
			public List<GradeData> grades {
				get { return _grades; }
				set { base.has_field.set_field (0, true); _grades = value; }
			}
			public bool HasGrades {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.grades = base.deserialize.read_obj_list<GradeData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.grades, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_itemChange {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private Int64 _type; // tag 0
			public Int64 type {
				get { return _type; }
				set { base.has_field.set_field (0, true); _type = value; }
			}
			public bool HasType {
				get { return base.has_field.has_field (0); }
			}

			private string _value; // tag 1
			public string value {
				get { return _value; }
				set { base.has_field.set_field (1, true); _value = value; }
			}
			public bool HasValue {
				get { return base.has_field.has_field (1); }
			}

			private double _change; // tag 2
			public double change {
				get { return _change; }
				set { base.has_field.set_field (2, true); _change = value; }
			}
			public bool HasChange {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _logType; // tag 3
			public Int64 logType {
				get { return _logType; }
				set { base.has_field.set_field (3, true); _logType = value; }
			}
			public bool HasLogType {
				get { return base.has_field.has_field (3); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.type = base.deserialize.read_integer ();
						break;
					case 1:
						this.value = base.deserialize.read_string ();
						break;
					case 2:
						this.change = base.deserialize.read_double ();
						break;
					case 3:
						this.logType = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.type, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.value, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_double (this.change, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.logType, 3);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_levelUp {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private string _name; // tag 0
			public string name {
				get { return _name; }
				set { base.has_field.set_field (0, true); _name = value; }
			}
			public bool HasName {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _level; // tag 1
			public Int64 level {
				get { return _level; }
				set { base.has_field.set_field (1, true); _level = value; }
			}
			public bool HasLevel {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _dbid; // tag 2
			public Int64 dbid {
				get { return _dbid; }
				set { base.has_field.set_field (2, true); _dbid = value; }
			}
			public bool HasDbid {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _gradeId; // tag 3
			public Int64 gradeId {
				get { return _gradeId; }
				set { base.has_field.set_field (3, true); _gradeId = value; }
			}
			public bool HasGradeId {
				get { return base.has_field.has_field (3); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.name = base.deserialize.read_string ();
						break;
					case 1:
						this.level = base.deserialize.read_integer ();
						break;
					case 2:
						this.dbid = base.deserialize.read_integer ();
						break;
					case 3:
						this.gradeId = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.name, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.level, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.dbid, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.gradeId, 3);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_loginRewardState {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private bool _loginGained; // tag 0
			public bool loginGained {
				get { return _loginGained; }
				set { base.has_field.set_field (0, true); _loginGained = value; }
			}
			public bool HasLoginGained {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.loginGained = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_boolean (this.loginGained, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_notifyAllMail {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private List<MailData> _recvMails; // tag 0
			public List<MailData> recvMails {
				get { return _recvMails; }
				set { base.has_field.set_field (0, true); _recvMails = value; }
			}
			public bool HasRecvMails {
				get { return base.has_field.has_field (0); }
			}

			private List<MailData> _sendMails; // tag 1
			public List<MailData> sendMails {
				get { return _sendMails; }
				set { base.has_field.set_field (1, true); _sendMails = value; }
			}
			public bool HasSendMails {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.recvMails = base.deserialize.read_obj_list<MailData> ();
						break;
					case 1:
						this.sendMails = base.deserialize.read_obj_list<MailData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.recvMails, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.sendMails, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_notifyItemLimit {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _id; // tag 0
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (0, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.id, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_notifyNewMail {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private MailData _mail; // tag 0
			public MailData mail {
				get { return _mail; }
				set { base.has_field.set_field (0, true); _mail = value; }
			}
			public bool HasMail {
				get { return base.has_field.has_field (0); }
			}

			private bool _recv; // tag 1
			public bool recv {
				get { return _recv; }
				set { base.has_field.set_field (1, true); _recv = value; }
			}
			public bool HasRecv {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.mail = base.deserialize.read_obj<MailData> ();
						break;
					case 1:
						this.recv = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.mail, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_boolean (this.recv, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_notifyWatchAd {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _adType; // tag 0
			public Int64 adType {
				get { return _adType; }
				set { base.has_field.set_field (0, true); _adType = value; }
			}
			public bool HasAdType {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.adType = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.adType, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_offline {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<ItemData> _rewards; // tag 0
			public List<ItemData> rewards {
				get { return _rewards; }
				set { base.has_field.set_field (0, true); _rewards = value; }
			}
			public bool HasRewards {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.rewards = base.deserialize.read_obj_list<ItemData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.rewards, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_offlineAd {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _value; // tag 0
			public Int64 value {
				get { return _value; }
				set { base.has_field.set_field (0, true); _value = value; }
			}
			public bool HasValue {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.value = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.value, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_shareTaskInfo {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<TaskData> _tasks; // tag 0
			public List<TaskData> tasks {
				get { return _tasks; }
				set { base.has_field.set_field (0, true); _tasks = value; }
			}
			public bool HasTasks {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.tasks = base.deserialize.read_obj_list<TaskData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.tasks, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_slotData {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<SlotData> _slots; // tag 0
			public List<SlotData> slots {
				get { return _slots; }
				set { base.has_field.set_field (0, true); _slots = value; }
			}
			public bool HasSlots {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.slots = base.deserialize.read_obj_list<SlotData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.slots, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_slotReward {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Int64 _slot; // tag 0
			public Int64 slot {
				get { return _slot; }
				set { base.has_field.set_field (0, true); _slot = value; }
			}
			public bool HasSlot {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _id; // tag 1
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (1, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _count; // tag 2
			public Int64 count {
				get { return _count; }
				set { base.has_field.set_field (2, true); _count = value; }
			}
			public bool HasCount {
				get { return base.has_field.has_field (2); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.slot = base.deserialize.read_integer ();
						break;
					case 1:
						this.id = base.deserialize.read_integer ();
						break;
					case 2:
						this.count = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.slot, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.id, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.count, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_speedupInfo {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _time; // tag 0
			public Int64 time {
				get { return _time; }
				set { base.has_field.set_field (0, true); _time = value; }
			}
			public bool HasTime {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _diamondSpeedUpCount; // tag 1
			public Int64 diamondSpeedUpCount {
				get { return _diamondSpeedUpCount; }
				set { base.has_field.set_field (1, true); _diamondSpeedUpCount = value; }
			}
			public bool HasDiamondSpeedUpCount {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.time = base.deserialize.read_integer ();
						break;
					case 1:
						this.diamondSpeedUpCount = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.time, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.diamondSpeedUpCount, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_syncData {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 21;
			
			
			private List<SlotData> _slots; // tag 0
			public List<SlotData> slots {
				get { return _slots; }
				set { base.has_field.set_field (0, true); _slots = value; }
			}
			public bool HasSlots {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _buyLv; // tag 1
			public Int64 buyLv {
				get { return _buyLv; }
				set { base.has_field.set_field (1, true); _buyLv = value; }
			}
			public bool HasBuyLv {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _level; // tag 2
			public Int64 level {
				get { return _level; }
				set { base.has_field.set_field (2, true); _level = value; }
			}
			public bool HasLevel {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _dbid; // tag 3
			public Int64 dbid {
				get { return _dbid; }
				set { base.has_field.set_field (3, true); _dbid = value; }
			}
			public bool HasDbid {
				get { return base.has_field.has_field (3); }
			}

			private string _name; // tag 4
			public string name {
				get { return _name; }
				set { base.has_field.set_field (4, true); _name = value; }
			}
			public bool HasName {
				get { return base.has_field.has_field (4); }
			}

			private Int64 _gainGoldCount; // tag 5
			public Int64 gainGoldCount {
				get { return _gainGoldCount; }
				set { base.has_field.set_field (5, true); _gainGoldCount = value; }
			}
			public bool HasGainGoldCount {
				get { return base.has_field.has_field (5); }
			}

			private Int64 _gainGoldProgress; // tag 6
			public Int64 gainGoldProgress {
				get { return _gainGoldProgress; }
				set { base.has_field.set_field (6, true); _gainGoldProgress = value; }
			}
			public bool HasGainGoldProgress {
				get { return base.has_field.has_field (6); }
			}

			private Int64 _gainGoldCdEndTime; // tag 7
			public Int64 gainGoldCdEndTime {
				get { return _gainGoldCdEndTime; }
				set { base.has_field.set_field (7, true); _gainGoldCdEndTime = value; }
			}
			public bool HasGainGoldCdEndTime {
				get { return base.has_field.has_field (7); }
			}

			private Int64 _diamondSpeedUpCount; // tag 8
			public Int64 diamondSpeedUpCount {
				get { return _diamondSpeedUpCount; }
				set { base.has_field.set_field (8, true); _diamondSpeedUpCount = value; }
			}
			public bool HasDiamondSpeedUpCount {
				get { return base.has_field.has_field (8); }
			}

			private ItemData _loginReward; // tag 9
			public ItemData loginReward {
				get { return _loginReward; }
				set { base.has_field.set_field (9, true); _loginReward = value; }
			}
			public bool HasLoginReward {
				get { return base.has_field.has_field (9); }
			}

			private bool _loginGained; // tag 10
			public bool loginGained {
				get { return _loginGained; }
				set { base.has_field.set_field (10, true); _loginGained = value; }
			}
			public bool HasLoginGained {
				get { return base.has_field.has_field (10); }
			}

			private Int64 _boxCount; // tag 11
			public Int64 boxCount {
				get { return _boxCount; }
				set { base.has_field.set_field (11, true); _boxCount = value; }
			}
			public bool HasBoxCount {
				get { return base.has_field.has_field (11); }
			}

			private Int64 _todayBoxCount; // tag 12
			public Int64 todayBoxCount {
				get { return _todayBoxCount; }
				set { base.has_field.set_field (12, true); _todayBoxCount = value; }
			}
			public bool HasTodayBoxCount {
				get { return base.has_field.has_field (12); }
			}

			private string _shareCode; // tag 13
			public string shareCode {
				get { return _shareCode; }
				set { base.has_field.set_field (13, true); _shareCode = value; }
			}
			public bool HasShareCode {
				get { return base.has_field.has_field (13); }
			}

			private string _invatedShareCode; // tag 14
			public string invatedShareCode {
				get { return _invatedShareCode; }
				set { base.has_field.set_field (14, true); _invatedShareCode = value; }
			}
			public bool HasInvatedShareCode {
				get { return base.has_field.has_field (14); }
			}

			private string _payaddr; // tag 15
			public string payaddr {
				get { return _payaddr; }
				set { base.has_field.set_field (15, true); _payaddr = value; }
			}
			public bool HasPayaddr {
				get { return base.has_field.has_field (15); }
			}

			private Int64 _vip; // tag 16
			public Int64 vip {
				get { return _vip; }
				set { base.has_field.set_field (16, true); _vip = value; }
			}
			public bool HasVip {
				get { return base.has_field.has_field (16); }
			}

			private double _cashOutMoney; // tag 17
			public double cashOutMoney {
				get { return _cashOutMoney; }
				set { base.has_field.set_field (17, true); _cashOutMoney = value; }
			}
			public bool HasCashOutMoney {
				get { return base.has_field.has_field (17); }
			}

			private Int64 _hongbaoyuCount; // tag 18
			public Int64 hongbaoyuCount {
				get { return _hongbaoyuCount; }
				set { base.has_field.set_field (18, true); _hongbaoyuCount = value; }
			}
			public bool HasHongbaoyuCount {
				get { return base.has_field.has_field (18); }
			}

			private double _recharge; // tag 19
			public double recharge {
				get { return _recharge; }
				set { base.has_field.set_field (19, true); _recharge = value; }
			}
			public bool HasRecharge {
				get { return base.has_field.has_field (19); }
			}

			private List<Int64> _vipRewards; // tag 20
			public List<Int64> vipRewards {
				get { return _vipRewards; }
				set { base.has_field.set_field (20, true); _vipRewards = value; }
			}
			public bool HasVipRewards {
				get { return base.has_field.has_field (20); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.slots = base.deserialize.read_obj_list<SlotData> ();
						break;
					case 1:
						this.buyLv = base.deserialize.read_integer ();
						break;
					case 2:
						this.level = base.deserialize.read_integer ();
						break;
					case 3:
						this.dbid = base.deserialize.read_integer ();
						break;
					case 4:
						this.name = base.deserialize.read_string ();
						break;
					case 5:
						this.gainGoldCount = base.deserialize.read_integer ();
						break;
					case 6:
						this.gainGoldProgress = base.deserialize.read_integer ();
						break;
					case 7:
						this.gainGoldCdEndTime = base.deserialize.read_integer ();
						break;
					case 8:
						this.diamondSpeedUpCount = base.deserialize.read_integer ();
						break;
					case 9:
						this.loginReward = base.deserialize.read_obj<ItemData> ();
						break;
					case 10:
						this.loginGained = base.deserialize.read_boolean ();
						break;
					case 11:
						this.boxCount = base.deserialize.read_integer ();
						break;
					case 12:
						this.todayBoxCount = base.deserialize.read_integer ();
						break;
					case 13:
						this.shareCode = base.deserialize.read_string ();
						break;
					case 14:
						this.invatedShareCode = base.deserialize.read_string ();
						break;
					case 15:
						this.payaddr = base.deserialize.read_string ();
						break;
					case 16:
						this.vip = base.deserialize.read_integer ();
						break;
					case 17:
						this.cashOutMoney = base.deserialize.read_double ();
						break;
					case 18:
						this.hongbaoyuCount = base.deserialize.read_integer ();
						break;
					case 19:
						this.recharge = base.deserialize.read_double ();
						break;
					case 20:
						this.vipRewards = base.deserialize.read_integer_list ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.slots, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.buyLv, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.level, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.dbid, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_string (this.name, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_integer (this.gainGoldCount, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_integer (this.gainGoldProgress, 6);
				}

				if (base.has_field.has_field (7)) {
					base.serialize.write_integer (this.gainGoldCdEndTime, 7);
				}

				if (base.has_field.has_field (8)) {
					base.serialize.write_integer (this.diamondSpeedUpCount, 8);
				}

				if (base.has_field.has_field (9)) {
					base.serialize.write_obj (this.loginReward, 9);
				}

				if (base.has_field.has_field (10)) {
					base.serialize.write_boolean (this.loginGained, 10);
				}

				if (base.has_field.has_field (11)) {
					base.serialize.write_integer (this.boxCount, 11);
				}

				if (base.has_field.has_field (12)) {
					base.serialize.write_integer (this.todayBoxCount, 12);
				}

				if (base.has_field.has_field (13)) {
					base.serialize.write_string (this.shareCode, 13);
				}

				if (base.has_field.has_field (14)) {
					base.serialize.write_string (this.invatedShareCode, 14);
				}

				if (base.has_field.has_field (15)) {
					base.serialize.write_string (this.payaddr, 15);
				}

				if (base.has_field.has_field (16)) {
					base.serialize.write_integer (this.vip, 16);
				}

				if (base.has_field.has_field (17)) {
					base.serialize.write_double (this.cashOutMoney, 17);
				}

				if (base.has_field.has_field (18)) {
					base.serialize.write_integer (this.hongbaoyuCount, 18);
				}

				if (base.has_field.has_field (19)) {
					base.serialize.write_double (this.recharge, 19);
				}

				if (base.has_field.has_field (20)) {
					base.serialize.write_integer (this.vipRewards, 20);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_taskInfo {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<TaskData> _tasks; // tag 0
			public List<TaskData> tasks {
				get { return _tasks; }
				set { base.has_field.set_field (0, true); _tasks = value; }
			}
			public bool HasTasks {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.tasks = base.deserialize.read_obj_list<TaskData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.tasks, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_tutorials {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<Int64> _tutorials; // tag 0
			public List<Int64> tutorials {
				get { return _tutorials; }
				set { base.has_field.set_field (0, true); _tutorials = value; }
			}
			public bool HasTutorials {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.tutorials = base.deserialize.read_integer_list ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.tutorials, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_wheelData {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Int64 _count; // tag 0
			public Int64 count {
				get { return _count; }
				set { base.has_field.set_field (0, true); _count = value; }
			}
			public bool HasCount {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _nextRestoreTime; // tag 1
			public Int64 nextRestoreTime {
				get { return _nextRestoreTime; }
				set { base.has_field.set_field (1, true); _nextRestoreTime = value; }
			}
			public bool HasNextRestoreTime {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _adCount; // tag 2
			public Int64 adCount {
				get { return _adCount; }
				set { base.has_field.set_field (2, true); _adCount = value; }
			}
			public bool HasAdCount {
				get { return base.has_field.has_field (2); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.count = base.deserialize.read_integer ();
						break;
					case 1:
						this.nextRestoreTime = base.deserialize.read_integer ();
						break;
					case 2:
						this.adCount = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.count, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.nextRestoreTime, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.adCount, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplays2c_workInfo {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Int64 _workId; // tag 0
			public Int64 workId {
				get { return _workId; }
				set { base.has_field.set_field (0, true); _workId = value; }
			}
			public bool HasWorkId {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _workEndTime; // tag 1
			public Int64 workEndTime {
				get { return _workEndTime; }
				set { base.has_field.set_field (1, true); _workEndTime = value; }
			}
			public bool HasWorkEndTime {
				get { return base.has_field.has_field (1); }
			}

			private List<WorkData> _workDatas; // tag 2
			public List<WorkData> workDatas {
				get { return _workDatas; }
				set { base.has_field.set_field (2, true); _workDatas = value; }
			}
			public bool HasWorkDatas {
				get { return base.has_field.has_field (2); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.workId = base.deserialize.read_integer ();
						break;
					case 1:
						this.workEndTime = base.deserialize.read_integer ();
						break;
					case 2:
						this.workDatas = base.deserialize.read_obj_list<WorkData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.workId, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.workEndTime, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_obj (this.workDatas, 2);
				}

				return base.serialize.close ();
			}
		}


	}


}

