// Generated by sprotodump. DO NOT EDIT!
// source: F:\new\unity\TEngine\Tools\sproto/../../Configs/Sproto/gametype.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace S2cSprotoType { 
	public class CashData : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _id; // tag 0
		public Int64 id {
			get { return _id; }
			set { base.has_field.set_field (0, true); _id = value; }
		}
		public bool HasId {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _time; // tag 1
		public Int64 time {
			get { return _time; }
			set { base.has_field.set_field (1, true); _time = value; }
		}
		public bool HasTime {
			get { return base.has_field.has_field (1); }
		}

		public CashData () : base(max_field_count) {}

		public CashData (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.id = base.deserialize.read_integer ();
					break;
				case 1:
					this.time = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.time, 1);
			}

			return base.serialize.close ();
		}
	}


	public class GradeData : SprotoTypeBase {
		private static int max_field_count = 4;
		
		
		private Int64 _id; // tag 0
		public Int64 id {
			get { return _id; }
			set { base.has_field.set_field (0, true); _id = value; }
		}
		public bool HasId {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _rewardState; // tag 1
		public Int64 rewardState {
			get { return _rewardState; }
			set { base.has_field.set_field (1, true); _rewardState = value; }
		}
		public bool HasRewardState {
			get { return base.has_field.has_field (1); }
		}

		private double _buyPrice; // tag 2
		public double buyPrice {
			get { return _buyPrice; }
			set { base.has_field.set_field (2, true); _buyPrice = value; }
		}
		public bool HasBuyPrice {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _diamondBuyPrice; // tag 3
		public Int64 diamondBuyPrice {
			get { return _diamondBuyPrice; }
			set { base.has_field.set_field (3, true); _diamondBuyPrice = value; }
		}
		public bool HasDiamondBuyPrice {
			get { return base.has_field.has_field (3); }
		}

		public GradeData () : base(max_field_count) {}

		public GradeData (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.id = base.deserialize.read_integer ();
					break;
				case 1:
					this.rewardState = base.deserialize.read_integer ();
					break;
				case 2:
					this.buyPrice = base.deserialize.read_double ();
					break;
				case 3:
					this.diamondBuyPrice = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.rewardState, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_double (this.buyPrice, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.diamondBuyPrice, 3);
			}

			return base.serialize.close ();
		}
	}


	public class ItemData : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _id; // tag 0
		public Int64 id {
			get { return _id; }
			set { base.has_field.set_field (0, true); _id = value; }
		}
		public bool HasId {
			get { return base.has_field.has_field (0); }
		}

		private double _count; // tag 1
		public double count {
			get { return _count; }
			set { base.has_field.set_field (1, true); _count = value; }
		}
		public bool HasCount {
			get { return base.has_field.has_field (1); }
		}

		public ItemData () : base(max_field_count) {}

		public ItemData (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.id = base.deserialize.read_integer ();
					break;
				case 1:
					this.count = base.deserialize.read_double ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_double (this.count, 1);
			}

			return base.serialize.close ();
		}
	}


	public class ItemDataStr : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _id; // tag 0
		public Int64 id {
			get { return _id; }
			set { base.has_field.set_field (0, true); _id = value; }
		}
		public bool HasId {
			get { return base.has_field.has_field (0); }
		}

		private string _count; // tag 1
		public string count {
			get { return _count; }
			set { base.has_field.set_field (1, true); _count = value; }
		}
		public bool HasCount {
			get { return base.has_field.has_field (1); }
		}

		public ItemDataStr () : base(max_field_count) {}

		public ItemDataStr (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.id = base.deserialize.read_integer ();
					break;
				case 1:
					this.count = base.deserialize.read_string ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.count, 1);
			}

			return base.serialize.close ();
		}
	}


	public class MailData : SprotoTypeBase {
		private static int max_field_count = 10;
		
		
		private Int64 _dbid; // tag 0
		public Int64 dbid {
			get { return _dbid; }
			set { base.has_field.set_field (0, true); _dbid = value; }
		}
		public bool HasDbid {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _sender; // tag 1
		public Int64 sender {
			get { return _sender; }
			set { base.has_field.set_field (1, true); _sender = value; }
		}
		public bool HasSender {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _receiver; // tag 2
		public Int64 receiver {
			get { return _receiver; }
			set { base.has_field.set_field (2, true); _receiver = value; }
		}
		public bool HasReceiver {
			get { return base.has_field.has_field (2); }
		}

		private string _senderName; // tag 3
		public string senderName {
			get { return _senderName; }
			set { base.has_field.set_field (3, true); _senderName = value; }
		}
		public bool HasSenderName {
			get { return base.has_field.has_field (3); }
		}

		private string _receiverName; // tag 4
		public string receiverName {
			get { return _receiverName; }
			set { base.has_field.set_field (4, true); _receiverName = value; }
		}
		public bool HasReceiverName {
			get { return base.has_field.has_field (4); }
		}

		private string _title; // tag 5
		public string title {
			get { return _title; }
			set { base.has_field.set_field (5, true); _title = value; }
		}
		public bool HasTitle {
			get { return base.has_field.has_field (5); }
		}

		private string _content; // tag 6
		public string content {
			get { return _content; }
			set { base.has_field.set_field (6, true); _content = value; }
		}
		public bool HasContent {
			get { return base.has_field.has_field (6); }
		}

		private List<ItemData> _attaches; // tag 7
		public List<ItemData> attaches {
			get { return _attaches; }
			set { base.has_field.set_field (7, true); _attaches = value; }
		}
		public bool HasAttaches {
			get { return base.has_field.has_field (7); }
		}

		private Int64 _time; // tag 8
		public Int64 time {
			get { return _time; }
			set { base.has_field.set_field (8, true); _time = value; }
		}
		public bool HasTime {
			get { return base.has_field.has_field (8); }
		}

		private Int64 _read; // tag 9
		public Int64 read {
			get { return _read; }
			set { base.has_field.set_field (9, true); _read = value; }
		}
		public bool HasRead {
			get { return base.has_field.has_field (9); }
		}

		public MailData () : base(max_field_count) {}

		public MailData (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.dbid = base.deserialize.read_integer ();
					break;
				case 1:
					this.sender = base.deserialize.read_integer ();
					break;
				case 2:
					this.receiver = base.deserialize.read_integer ();
					break;
				case 3:
					this.senderName = base.deserialize.read_string ();
					break;
				case 4:
					this.receiverName = base.deserialize.read_string ();
					break;
				case 5:
					this.title = base.deserialize.read_string ();
					break;
				case 6:
					this.content = base.deserialize.read_string ();
					break;
				case 7:
					this.attaches = base.deserialize.read_obj_list<ItemData> ();
					break;
				case 8:
					this.time = base.deserialize.read_integer ();
					break;
				case 9:
					this.read = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.dbid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.sender, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.receiver, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_string (this.senderName, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_string (this.receiverName, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_string (this.title, 5);
			}

			if (base.has_field.has_field (6)) {
				base.serialize.write_string (this.content, 6);
			}

			if (base.has_field.has_field (7)) {
				base.serialize.write_obj (this.attaches, 7);
			}

			if (base.has_field.has_field (8)) {
				base.serialize.write_integer (this.time, 8);
			}

			if (base.has_field.has_field (9)) {
				base.serialize.write_integer (this.read, 9);
			}

			return base.serialize.close ();
		}
	}


	public class PlayerInfo : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _dbid; // tag 0
		public Int64 dbid {
			get { return _dbid; }
			set { base.has_field.set_field (0, true); _dbid = value; }
		}
		public bool HasDbid {
			get { return base.has_field.has_field (0); }
		}

		private string _name; // tag 1
		public string name {
			get { return _name; }
			set { base.has_field.set_field (1, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (1); }
		}

		public PlayerInfo () : base(max_field_count) {}

		public PlayerInfo (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.dbid = base.deserialize.read_integer ();
					break;
				case 1:
					this.name = base.deserialize.read_string ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.dbid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.name, 1);
			}

			return base.serialize.close ();
		}
	}


	public class Pos : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _x; // tag 0
		public Int64 x {
			get { return _x; }
			set { base.has_field.set_field (0, true); _x = value; }
		}
		public bool HasX {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _y; // tag 1
		public Int64 y {
			get { return _y; }
			set { base.has_field.set_field (1, true); _y = value; }
		}
		public bool HasY {
			get { return base.has_field.has_field (1); }
		}

		public Pos () : base(max_field_count) {}

		public Pos (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.x = base.deserialize.read_integer ();
					break;
				case 1:
					this.y = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.x, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.y, 1);
			}

			return base.serialize.close ();
		}
	}


	public class RankData : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _dbid; // tag 0
		public Int64 dbid {
			get { return _dbid; }
			set { base.has_field.set_field (0, true); _dbid = value; }
		}
		public bool HasDbid {
			get { return base.has_field.has_field (0); }
		}

		private string _name; // tag 1
		public string name {
			get { return _name; }
			set { base.has_field.set_field (1, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (1); }
		}

		private double _value; // tag 2
		public double value {
			get { return _value; }
			set { base.has_field.set_field (2, true); _value = value; }
		}
		public bool HasValue {
			get { return base.has_field.has_field (2); }
		}

		public RankData () : base(max_field_count) {}

		public RankData (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.dbid = base.deserialize.read_integer ();
					break;
				case 1:
					this.name = base.deserialize.read_string ();
					break;
				case 2:
					this.value = base.deserialize.read_double ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.dbid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.name, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_double (this.value, 2);
			}

			return base.serialize.close ();
		}
	}


	public class SlotData : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _id; // tag 0
		public Int64 id {
			get { return _id; }
			set { base.has_field.set_field (0, true); _id = value; }
		}
		public bool HasId {
			get { return base.has_field.has_field (0); }
		}

		private bool _box; // tag 1
		public bool box {
			get { return _box; }
			set { base.has_field.set_field (1, true); _box = value; }
		}
		public bool HasBox {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _invalidTime; // tag 2
		public Int64 invalidTime {
			get { return _invalidTime; }
			set { base.has_field.set_field (2, true); _invalidTime = value; }
		}
		public bool HasInvalidTime {
			get { return base.has_field.has_field (2); }
		}

		public SlotData () : base(max_field_count) {}

		public SlotData (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.id = base.deserialize.read_integer ();
					break;
				case 1:
					this.box = base.deserialize.read_boolean ();
					break;
				case 2:
					this.invalidTime = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_boolean (this.box, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.invalidTime, 2);
			}

			return base.serialize.close ();
		}
	}


	public class TaskData : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _id; // tag 0
		public Int64 id {
			get { return _id; }
			set { base.has_field.set_field (0, true); _id = value; }
		}
		public bool HasId {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _progress; // tag 1
		public Int64 progress {
			get { return _progress; }
			set { base.has_field.set_field (1, true); _progress = value; }
		}
		public bool HasProgress {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _status; // tag 2
		public Int64 status {
			get { return _status; }
			set { base.has_field.set_field (2, true); _status = value; }
		}
		public bool HasStatus {
			get { return base.has_field.has_field (2); }
		}

		public TaskData () : base(max_field_count) {}

		public TaskData (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.id = base.deserialize.read_integer ();
					break;
				case 1:
					this.progress = base.deserialize.read_integer ();
					break;
				case 2:
					this.status = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.progress, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.status, 2);
			}

			return base.serialize.close ();
		}
	}


	public class WorkData : SprotoTypeBase {
		private static int max_field_count = 5;
		
		
		private Int64 _cdTime; // tag 0
		public Int64 cdTime {
			get { return _cdTime; }
			set { base.has_field.set_field (0, true); _cdTime = value; }
		}
		public bool HasCdTime {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _count; // tag 1
		public Int64 count {
			get { return _count; }
			set { base.has_field.set_field (1, true); _count = value; }
		}
		public bool HasCount {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _id; // tag 2
		public Int64 id {
			get { return _id; }
			set { base.has_field.set_field (2, true); _id = value; }
		}
		public bool HasId {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _rwType; // tag 3
		public Int64 rwType {
			get { return _rwType; }
			set { base.has_field.set_field (3, true); _rwType = value; }
		}
		public bool HasRwType {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _rwCount; // tag 4
		public Int64 rwCount {
			get { return _rwCount; }
			set { base.has_field.set_field (4, true); _rwCount = value; }
		}
		public bool HasRwCount {
			get { return base.has_field.has_field (4); }
		}

		public WorkData () : base(max_field_count) {}

		public WorkData (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.cdTime = base.deserialize.read_integer ();
					break;
				case 1:
					this.count = base.deserialize.read_integer ();
					break;
				case 2:
					this.id = base.deserialize.read_integer ();
					break;
				case 3:
					this.rwType = base.deserialize.read_integer ();
					break;
				case 4:
					this.rwCount = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.cdTime, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.count, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.id, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.rwType, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.rwCount, 4);
			}

			return base.serialize.close ();
		}
	}


	public class package : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _type; // tag 0
		public Int64 type {
			get { return _type; }
			set { base.has_field.set_field (0, true); _type = value; }
		}
		public bool HasType {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _session; // tag 1
		public Int64 session {
			get { return _session; }
			set { base.has_field.set_field (1, true); _session = value; }
		}
		public bool HasSession {
			get { return base.has_field.has_field (1); }
		}

		public package () : base(max_field_count) {}

		public package (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.type = base.deserialize.read_integer ();
					break;
				case 1:
					this.session = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.type, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.session, 1);
			}

			return base.serialize.close ();
		}
	}


}

