// Generated by sprotodump. DO NOT EDIT!
// source: F:\new\unity\TEngine\Tools\sproto/../../Configs/Sproto/gameplayc2s.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace C2sSprotoType { 
	public class cs_send_heart_beat {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


	}


	public class cs_sene_gm_command {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private string _cmd; // tag 0
			public string cmd {
				get { return _cmd; }
				set { base.has_field.set_field (0, true); _cmd = value; }
			}
			public bool HasCmd {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.cmd = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.cmd, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_archiveGainReward {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _lv; // tag 0
			public Int64 lv {
				get { return _lv; }
				set { base.has_field.set_field (0, true); _lv = value; }
			}
			public bool HasLv {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.lv = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.lv, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_box {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private Int64 _count; // tag 0
			public Int64 count {
				get { return _count; }
				set { base.has_field.set_field (0, true); _count = value; }
			}
			public bool HasCount {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _todayBoxCount; // tag 1
			public Int64 todayBoxCount {
				get { return _todayBoxCount; }
				set { base.has_field.set_field (1, true); _todayBoxCount = value; }
			}
			public bool HasTodayBoxCount {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _itemId; // tag 2
			public Int64 itemId {
				get { return _itemId; }
				set { base.has_field.set_field (2, true); _itemId = value; }
			}
			public bool HasItemId {
				get { return base.has_field.has_field (2); }
			}

			private double _itemCount; // tag 3
			public double itemCount {
				get { return _itemCount; }
				set { base.has_field.set_field (3, true); _itemCount = value; }
			}
			public bool HasItemCount {
				get { return base.has_field.has_field (3); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.count = base.deserialize.read_integer ();
						break;
					case 1:
						this.todayBoxCount = base.deserialize.read_integer ();
						break;
					case 2:
						this.itemId = base.deserialize.read_integer ();
						break;
					case 3:
						this.itemCount = base.deserialize.read_double ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.count, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.todayBoxCount, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.itemId, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_double (this.itemCount, 3);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_buyItem {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _typ; // tag 0
			public Int64 typ {
				get { return _typ; }
				set { base.has_field.set_field (0, true); _typ = value; }
			}
			public bool HasTyp {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _id; // tag 1
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (1, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.typ = base.deserialize.read_integer ();
						break;
					case 1:
						this.id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.typ, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.id, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _slot; // tag 0
			public Int64 slot {
				get { return _slot; }
				set { base.has_field.set_field (0, true); _slot = value; }
			}
			public bool HasSlot {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.slot = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.slot, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_cashOut {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _id; // tag 0
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (0, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.id, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _rt; // tag 0
			public Int64 rt {
				get { return _rt; }
				set { base.has_field.set_field (0, true); _rt = value; }
			}
			public bool HasRt {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.rt = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.rt, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_composeAvartar {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _srcSlot; // tag 0
			public Int64 srcSlot {
				get { return _srcSlot; }
				set { base.has_field.set_field (0, true); _srcSlot = value; }
			}
			public bool HasSrcSlot {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _destSlot; // tag 1
			public Int64 destSlot {
				get { return _destSlot; }
				set { base.has_field.set_field (1, true); _destSlot = value; }
			}
			public bool HasDestSlot {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.srcSlot = base.deserialize.read_integer ();
						break;
					case 1:
						this.destSlot = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.srcSlot, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.destSlot, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private SlotData _srcSlotData; // tag 0
			public SlotData srcSlotData {
				get { return _srcSlotData; }
				set { base.has_field.set_field (0, true); _srcSlotData = value; }
			}
			public bool HasSrcSlotData {
				get { return base.has_field.has_field (0); }
			}

			private SlotData _destSlotData; // tag 1
			public SlotData destSlotData {
				get { return _destSlotData; }
				set { base.has_field.set_field (1, true); _destSlotData = value; }
			}
			public bool HasDestSlotData {
				get { return base.has_field.has_field (1); }
			}

			private bool _rt; // tag 2
			public bool rt {
				get { return _rt; }
				set { base.has_field.set_field (2, true); _rt = value; }
			}
			public bool HasRt {
				get { return base.has_field.has_field (2); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.srcSlotData = base.deserialize.read_obj<SlotData> ();
						break;
					case 1:
						this.destSlotData = base.deserialize.read_obj<SlotData> ();
						break;
					case 2:
						this.rt = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.srcSlotData, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.destSlotData, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_boolean (this.rt, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_composeSuperAvatar {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<Int64> _slots; // tag 0
			public List<Int64> slots {
				get { return _slots; }
				set { base.has_field.set_field (0, true); _slots = value; }
			}
			public bool HasSlots {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.slots = base.deserialize.read_integer_list ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.slots, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_createAvartar {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private Int64 _slot; // tag 0
			public Int64 slot {
				get { return _slot; }
				set { base.has_field.set_field (0, true); _slot = value; }
			}
			public bool HasSlot {
				get { return base.has_field.has_field (0); }
			}

			private SlotData _slotData; // tag 1
			public SlotData slotData {
				get { return _slotData; }
				set { base.has_field.set_field (1, true); _slotData = value; }
			}
			public bool HasSlotData {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _buyLv; // tag 2
			public Int64 buyLv {
				get { return _buyLv; }
				set { base.has_field.set_field (2, true); _buyLv = value; }
			}
			public bool HasBuyLv {
				get { return base.has_field.has_field (2); }
			}

			private double _buyPrice; // tag 3
			public double buyPrice {
				get { return _buyPrice; }
				set { base.has_field.set_field (3, true); _buyPrice = value; }
			}
			public bool HasBuyPrice {
				get { return base.has_field.has_field (3); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.slot = base.deserialize.read_integer ();
						break;
					case 1:
						this.slotData = base.deserialize.read_obj<SlotData> ();
						break;
					case 2:
						this.buyLv = base.deserialize.read_integer ();
						break;
					case 3:
						this.buyPrice = base.deserialize.read_double ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.slot, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.slotData, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.buyLv, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_double (this.buyPrice, 3);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_deleteMail {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _mailId; // tag 0
			public Int64 mailId {
				get { return _mailId; }
				set { base.has_field.set_field (0, true); _mailId = value; }
			}
			public bool HasMailId {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _receiver; // tag 1
			public Int64 receiver {
				get { return _receiver; }
				set { base.has_field.set_field (1, true); _receiver = value; }
			}
			public bool HasReceiver {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.mailId = base.deserialize.read_integer ();
						break;
					case 1:
						this.receiver = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.mailId, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.receiver, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_gainBonusData {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private Int64 _todayBonus; // tag 0
			public Int64 todayBonus {
				get { return _todayBonus; }
				set { base.has_field.set_field (0, true); _todayBonus = value; }
			}
			public bool HasTodayBonus {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _managerCount; // tag 1
			public Int64 managerCount {
				get { return _managerCount; }
				set { base.has_field.set_field (1, true); _managerCount = value; }
			}
			public bool HasManagerCount {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _tempManagerCount; // tag 2
			public Int64 tempManagerCount {
				get { return _tempManagerCount; }
				set { base.has_field.set_field (2, true); _tempManagerCount = value; }
			}
			public bool HasTempManagerCount {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _myProgress; // tag 3
			public Int64 myProgress {
				get { return _myProgress; }
				set { base.has_field.set_field (3, true); _myProgress = value; }
			}
			public bool HasMyProgress {
				get { return base.has_field.has_field (3); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.todayBonus = base.deserialize.read_integer ();
						break;
					case 1:
						this.managerCount = base.deserialize.read_integer ();
						break;
					case 2:
						this.tempManagerCount = base.deserialize.read_integer ();
						break;
					case 3:
						this.myProgress = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.todayBonus, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.managerCount, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.tempManagerCount, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.myProgress, 3);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_gainGold {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 5;
			
			
			private bool _rt; // tag 0
			public bool rt {
				get { return _rt; }
				set { base.has_field.set_field (0, true); _rt = value; }
			}
			public bool HasRt {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _count; // tag 1
			public Int64 count {
				get { return _count; }
				set { base.has_field.set_field (1, true); _count = value; }
			}
			public bool HasCount {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _progress; // tag 2
			public Int64 progress {
				get { return _progress; }
				set { base.has_field.set_field (2, true); _progress = value; }
			}
			public bool HasProgress {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _cdEnd; // tag 3
			public Int64 cdEnd {
				get { return _cdEnd; }
				set { base.has_field.set_field (3, true); _cdEnd = value; }
			}
			public bool HasCdEnd {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _gold; // tag 4
			public Int64 gold {
				get { return _gold; }
				set { base.has_field.set_field (4, true); _gold = value; }
			}
			public bool HasGold {
				get { return base.has_field.has_field (4); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.rt = base.deserialize.read_boolean ();
						break;
					case 1:
						this.count = base.deserialize.read_integer ();
						break;
					case 2:
						this.progress = base.deserialize.read_integer ();
						break;
					case 3:
						this.cdEnd = base.deserialize.read_integer ();
						break;
					case 4:
						this.gold = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_boolean (this.rt, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.count, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.progress, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.cdEnd, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.gold, 4);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_gainHongBao {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _id; // tag 0
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (0, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.id, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_gainHongBaoYu {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_gainShareTaskReward {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _id; // tag 0
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (0, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.id, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_gainTaskReward {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _id; // tag 0
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (0, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.id, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_gainVipReward {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _vip; // tag 0
			public Int64 vip {
				get { return _vip; }
				set { base.has_field.set_field (0, true); _vip = value; }
			}
			public bool HasVip {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.vip = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.vip, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<Int64> _vipRewards; // tag 0
			public List<Int64> vipRewards {
				get { return _vipRewards; }
				set { base.has_field.set_field (0, true); _vipRewards = value; }
			}
			public bool HasVipRewards {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.vipRewards = base.deserialize.read_integer_list ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.vipRewards, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_gmRecharge {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private string _id; // tag 0
			public string id {
				get { return _id; }
				set { base.has_field.set_field (0, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.id = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.id, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_hongbaoyu {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_inputPayAddr {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private string _addr; // tag 0
			public string addr {
				get { return _addr; }
				set { base.has_field.set_field (0, true); _addr = value; }
			}
			public bool HasAddr {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.addr = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.addr, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_inputShareCode {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private string _code; // tag 0
			public string code {
				get { return _code; }
				set { base.has_field.set_field (0, true); _code = value; }
			}
			public bool HasCode {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.code = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.code, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_openBox {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _slot; // tag 0
			public Int64 slot {
				get { return _slot; }
				set { base.has_field.set_field (0, true); _slot = value; }
			}
			public bool HasSlot {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.slot = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.slot, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private SlotData _slotData; // tag 0
			public SlotData slotData {
				get { return _slotData; }
				set { base.has_field.set_field (0, true); _slotData = value; }
			}
			public bool HasSlotData {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _id; // tag 1
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (1, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (1); }
			}

			private double _count; // tag 2
			public double count {
				get { return _count; }
				set { base.has_field.set_field (2, true); _count = value; }
			}
			public bool HasCount {
				get { return base.has_field.has_field (2); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.slotData = base.deserialize.read_obj<SlotData> ();
						break;
					case 1:
						this.id = base.deserialize.read_integer ();
						break;
					case 2:
						this.count = base.deserialize.read_double ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.slotData, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.id, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_double (this.count, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_rankData {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private string _addr; // tag 0
			public string addr {
				get { return _addr; }
				set { base.has_field.set_field (0, true); _addr = value; }
			}
			public bool HasAddr {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.addr = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.addr, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<RankData> _ranks; // tag 0
			public List<RankData> ranks {
				get { return _ranks; }
				set { base.has_field.set_field (0, true); _ranks = value; }
			}
			public bool HasRanks {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.ranks = base.deserialize.read_obj_list<RankData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.ranks, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_readMail {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _mailId; // tag 0
			public Int64 mailId {
				get { return _mailId; }
				set { base.has_field.set_field (0, true); _mailId = value; }
			}
			public bool HasMailId {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _receiver; // tag 1
			public Int64 receiver {
				get { return _receiver; }
				set { base.has_field.set_field (1, true); _receiver = value; }
			}
			public bool HasReceiver {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.mailId = base.deserialize.read_integer ();
						break;
					case 1:
						this.receiver = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.mailId, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.receiver, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_recycle {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _slot; // tag 0
			public Int64 slot {
				get { return _slot; }
				set { base.has_field.set_field (0, true); _slot = value; }
			}
			public bool HasSlot {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.slot = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.slot, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _count; // tag 0
			public Int64 count {
				get { return _count; }
				set { base.has_field.set_field (0, true); _count = value; }
			}
			public bool HasCount {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.count = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.count, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_searchName {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _condition; // tag 0
			public Int64 condition {
				get { return _condition; }
				set { base.has_field.set_field (0, true); _condition = value; }
			}
			public bool HasCondition {
				get { return base.has_field.has_field (0); }
			}

			private string _value; // tag 1
			public string value {
				get { return _value; }
				set { base.has_field.set_field (1, true); _value = value; }
			}
			public bool HasValue {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.condition = base.deserialize.read_integer ();
						break;
					case 1:
						this.value = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.condition, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.value, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<PlayerInfo> _rts; // tag 0
			public List<PlayerInfo> rts {
				get { return _rts; }
				set { base.has_field.set_field (0, true); _rts = value; }
			}
			public bool HasRts {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.rts = base.deserialize.read_obj_list<PlayerInfo> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.rts, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_sendMail {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private Int64 _dbid; // tag 0
			public Int64 dbid {
				get { return _dbid; }
				set { base.has_field.set_field (0, true); _dbid = value; }
			}
			public bool HasDbid {
				get { return base.has_field.has_field (0); }
			}

			private string _title; // tag 1
			public string title {
				get { return _title; }
				set { base.has_field.set_field (1, true); _title = value; }
			}
			public bool HasTitle {
				get { return base.has_field.has_field (1); }
			}

			private string _content; // tag 2
			public string content {
				get { return _content; }
				set { base.has_field.set_field (2, true); _content = value; }
			}
			public bool HasContent {
				get { return base.has_field.has_field (2); }
			}

			private List<ItemData> _attaches; // tag 3
			public List<ItemData> attaches {
				get { return _attaches; }
				set { base.has_field.set_field (3, true); _attaches = value; }
			}
			public bool HasAttaches {
				get { return base.has_field.has_field (3); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.dbid = base.deserialize.read_integer ();
						break;
					case 1:
						this.title = base.deserialize.read_string ();
						break;
					case 2:
						this.content = base.deserialize.read_string ();
						break;
					case 3:
						this.attaches = base.deserialize.read_obj_list<ItemData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.dbid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.title, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_string (this.content, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_obj (this.attaches, 3);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_shareFinish {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private string _userdata; // tag 0
			public string userdata {
				get { return _userdata; }
				set { base.has_field.set_field (0, true); _userdata = value; }
			}
			public bool HasUserdata {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.userdata = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.userdata, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_speedup {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_watchAD {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _typ; // tag 0
			public Int64 typ {
				get { return _typ; }
				set { base.has_field.set_field (0, true); _typ = value; }
			}
			public bool HasTyp {
				get { return base.has_field.has_field (0); }
			}

			private string _userdata; // tag 1
			public string userdata {
				get { return _userdata; }
				set { base.has_field.set_field (1, true); _userdata = value; }
			}
			public bool HasUserdata {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.typ = base.deserialize.read_integer ();
						break;
					case 1:
						this.userdata = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.typ, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.userdata, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_watchEndAD {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private bool _giveup; // tag 0
			public bool giveup {
				get { return _giveup; }
				set { base.has_field.set_field (0, true); _giveup = value; }
			}
			public bool HasGiveup {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.giveup = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_boolean (this.giveup, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _typ; // tag 0
			public Int64 typ {
				get { return _typ; }
				set { base.has_field.set_field (0, true); _typ = value; }
			}
			public bool HasTyp {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.typ = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.typ, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_wheel {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _index; // tag 0
			public Int64 index {
				get { return _index; }
				set { base.has_field.set_field (0, true); _index = value; }
			}
			public bool HasIndex {
				get { return base.has_field.has_field (0); }
			}

			private ItemData _rw; // tag 1
			public ItemData rw {
				get { return _rw; }
				set { base.has_field.set_field (1, true); _rw = value; }
			}
			public bool HasRw {
				get { return base.has_field.has_field (1); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.index = base.deserialize.read_integer ();
						break;
					case 1:
						this.rw = base.deserialize.read_obj<ItemData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.index, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.rw, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_work {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _id; // tag 0
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (0, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.id, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class gameplayc2s_workReward {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _id; // tag 0
			public Int64 id {
				get { return _id; }
				set { base.has_field.set_field (0, true); _id = value; }
			}
			public bool HasId {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.id, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private ItemData _reward; // tag 0
			public ItemData reward {
				get { return _reward; }
				set { base.has_field.set_field (0, true); _reward = value; }
			}
			public bool HasReward {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.reward = base.deserialize.read_obj<ItemData> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.reward, 0);
				}

				return base.serialize.close ();
			}
		}


	}


}

