// Generated by sprotodump. DO NOT EDIT!
// source: F:\new\unity\TEngine\Tools\sproto/../../Configs/Sproto/room_s2c.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace S2cSprotoType { 
	public class room_member_info : SprotoTypeBase {
		private static int max_field_count = 4;
		
		
		private Int64 _dbid; // tag 0
		public Int64 dbid {
			get { return _dbid; }
			set { base.has_field.set_field (0, true); _dbid = value; }
		}
		public bool HasDbid {
			get { return base.has_field.has_field (0); }
		}

		private string _name; // tag 1
		public string name {
			get { return _name; }
			set { base.has_field.set_field (1, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (1); }
		}

		private string _head; // tag 2
		public string head {
			get { return _head; }
			set { base.has_field.set_field (2, true); _head = value; }
		}
		public bool HasHead {
			get { return base.has_field.has_field (2); }
		}

		private bool _ready; // tag 3
		public bool ready {
			get { return _ready; }
			set { base.has_field.set_field (3, true); _ready = value; }
		}
		public bool HasReady {
			get { return base.has_field.has_field (3); }
		}

		public room_member_info () : base(max_field_count) {}

		public room_member_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.dbid = base.deserialize.read_integer ();
					break;
				case 1:
					this.name = base.deserialize.read_string ();
					break;
				case 2:
					this.head = base.deserialize.read_string ();
					break;
				case 3:
					this.ready = base.deserialize.read_boolean ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.dbid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.name, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_string (this.head, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_boolean (this.ready, 3);
			}

			return base.serialize.close ();
		}
	}


	public class sc_room_enter {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 5;
			
			
			private Int64 _roomid; // tag 0
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (0, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _count; // tag 1
			public Int64 count {
				get { return _count; }
				set { base.has_field.set_field (1, true); _count = value; }
			}
			public bool HasCount {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _cost; // tag 2
			public Int64 cost {
				get { return _cost; }
				set { base.has_field.set_field (2, true); _cost = value; }
			}
			public bool HasCost {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _owner; // tag 3
			public Int64 owner {
				get { return _owner; }
				set { base.has_field.set_field (3, true); _owner = value; }
			}
			public bool HasOwner {
				get { return base.has_field.has_field (3); }
			}

			private List<room_member_info> _players; // tag 4
			public List<room_member_info> players {
				get { return _players; }
				set { base.has_field.set_field (4, true); _players = value; }
			}
			public bool HasPlayers {
				get { return base.has_field.has_field (4); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.roomid = base.deserialize.read_integer ();
						break;
					case 1:
						this.count = base.deserialize.read_integer ();
						break;
					case 2:
						this.cost = base.deserialize.read_integer ();
						break;
					case 3:
						this.owner = base.deserialize.read_integer ();
						break;
					case 4:
						this.players = base.deserialize.read_obj_list<room_member_info> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.roomid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.count, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.cost, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.owner, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_obj (this.players, 4);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_room_match_cancel_ret {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _ret; // tag 0
			public Int64 ret {
				get { return _ret; }
				set { base.has_field.set_field (0, true); _ret = value; }
			}
			public bool HasRet {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.ret = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.ret, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_room_match_ret {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _ret; // tag 0
			public Int64 ret {
				get { return _ret; }
				set { base.has_field.set_field (0, true); _ret = value; }
			}
			public bool HasRet {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.ret = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.ret, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_room_otherplayer_enter {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _roomid; // tag 0
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (0, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (0); }
			}

			private room_member_info _player; // tag 1
			public room_member_info player {
				get { return _player; }
				set { base.has_field.set_field (1, true); _player = value; }
			}
			public bool HasPlayer {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.roomid = base.deserialize.read_integer ();
						break;
					case 1:
						this.player = base.deserialize.read_obj<room_member_info> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.roomid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.player, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_room_player_leave {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private Int64 _roomid; // tag 0
			public Int64 roomid {
				get { return _roomid; }
				set { base.has_field.set_field (0, true); _roomid = value; }
			}
			public bool HasRoomid {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _dbid; // tag 1
			public Int64 dbid {
				get { return _dbid; }
				set { base.has_field.set_field (1, true); _dbid = value; }
			}
			public bool HasDbid {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _owner; // tag 2
			public Int64 owner {
				get { return _owner; }
				set { base.has_field.set_field (2, true); _owner = value; }
			}
			public bool HasOwner {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _reason; // tag 3
			public Int64 reason {
				get { return _reason; }
				set { base.has_field.set_field (3, true); _reason = value; }
			}
			public bool HasReason {
				get { return base.has_field.has_field (3); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.roomid = base.deserialize.read_integer ();
						break;
					case 1:
						this.dbid = base.deserialize.read_integer ();
						break;
					case 2:
						this.owner = base.deserialize.read_integer ();
						break;
					case 3:
						this.reason = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.roomid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.dbid, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.owner, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.reason, 3);
				}

				return base.serialize.close ();
			}
		}


	}


	public class sc_room_ready {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _dbid; // tag 0
			public Int64 dbid {
				get { return _dbid; }
				set { base.has_field.set_field (0, true); _dbid = value; }
			}
			public bool HasDbid {
				get { return base.has_field.has_field (0); }
			}

			private bool _ready; // tag 1
			public bool ready {
				get { return _ready; }
				set { base.has_field.set_field (1, true); _ready = value; }
			}
			public bool HasReady {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.dbid = base.deserialize.read_integer ();
						break;
					case 1:
						this.ready = base.deserialize.read_boolean ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.dbid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_boolean (this.ready, 1);
				}

				return base.serialize.close ();
			}
		}


	}


}

