// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class S2cProtocol : ProtocolBase {
	public static  S2cProtocol Instance = new S2cProtocol();
	private S2cProtocol() {
		Protocol.SetProtocol<gameplays2c_bagInfo> (gameplays2c_bagInfo.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_bagInfo.request> (gameplays2c_bagInfo.Tag);

		Protocol.SetProtocol<gameplays2c_cashData> (gameplays2c_cashData.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_cashData.request> (gameplays2c_cashData.Tag);

		Protocol.SetProtocol<gameplays2c_finishTutorial> (gameplays2c_finishTutorial.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_finishTutorial.request> (gameplays2c_finishTutorial.Tag);

		Protocol.SetProtocol<gameplays2c_gradeInfo> (gameplays2c_gradeInfo.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_gradeInfo.request> (gameplays2c_gradeInfo.Tag);

		Protocol.SetProtocol<gameplays2c_itemChange> (gameplays2c_itemChange.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_itemChange.request> (gameplays2c_itemChange.Tag);

		Protocol.SetProtocol<gameplays2c_levelUp> (gameplays2c_levelUp.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_levelUp.request> (gameplays2c_levelUp.Tag);

		Protocol.SetProtocol<gameplays2c_loginRewardState> (gameplays2c_loginRewardState.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_loginRewardState.request> (gameplays2c_loginRewardState.Tag);

		Protocol.SetProtocol<gameplays2c_notifyAllMail> (gameplays2c_notifyAllMail.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_notifyAllMail.request> (gameplays2c_notifyAllMail.Tag);

		Protocol.SetProtocol<gameplays2c_notifyItemLimit> (gameplays2c_notifyItemLimit.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_notifyItemLimit.request> (gameplays2c_notifyItemLimit.Tag);

		Protocol.SetProtocol<gameplays2c_notifyNewMail> (gameplays2c_notifyNewMail.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_notifyNewMail.request> (gameplays2c_notifyNewMail.Tag);

		Protocol.SetProtocol<gameplays2c_notifyWatchAd> (gameplays2c_notifyWatchAd.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_notifyWatchAd.request> (gameplays2c_notifyWatchAd.Tag);

		Protocol.SetProtocol<gameplays2c_offline> (gameplays2c_offline.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_offline.request> (gameplays2c_offline.Tag);

		Protocol.SetProtocol<gameplays2c_offlineAd> (gameplays2c_offlineAd.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_offlineAd.request> (gameplays2c_offlineAd.Tag);

		Protocol.SetProtocol<gameplays2c_shareTaskInfo> (gameplays2c_shareTaskInfo.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_shareTaskInfo.request> (gameplays2c_shareTaskInfo.Tag);

		Protocol.SetProtocol<gameplays2c_slotData> (gameplays2c_slotData.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_slotData.request> (gameplays2c_slotData.Tag);

		Protocol.SetProtocol<gameplays2c_slotReward> (gameplays2c_slotReward.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_slotReward.request> (gameplays2c_slotReward.Tag);

		Protocol.SetProtocol<gameplays2c_speedupInfo> (gameplays2c_speedupInfo.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_speedupInfo.request> (gameplays2c_speedupInfo.Tag);

		Protocol.SetProtocol<gameplays2c_syncData> (gameplays2c_syncData.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_syncData.request> (gameplays2c_syncData.Tag);

		Protocol.SetProtocol<gameplays2c_taskInfo> (gameplays2c_taskInfo.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_taskInfo.request> (gameplays2c_taskInfo.Tag);

		Protocol.SetProtocol<gameplays2c_tutorials> (gameplays2c_tutorials.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_tutorials.request> (gameplays2c_tutorials.Tag);

		Protocol.SetProtocol<gameplays2c_wheelData> (gameplays2c_wheelData.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_wheelData.request> (gameplays2c_wheelData.Tag);

		Protocol.SetProtocol<gameplays2c_workInfo> (gameplays2c_workInfo.Tag);
		Protocol.SetRequest<S2cSprotoType.gameplays2c_workInfo.request> (gameplays2c_workInfo.Tag);

		Protocol.SetProtocol<sc_actor_eliminate_count_info> (sc_actor_eliminate_count_info.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_actor_eliminate_count_info.request> (sc_actor_eliminate_count_info.Tag);

		Protocol.SetProtocol<sc_base_game_time> (sc_base_game_time.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_base_game_time.request> (sc_base_game_time.Tag);

		Protocol.SetProtocol<sc_base_open_day> (sc_base_open_day.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_base_open_day.request> (sc_base_open_day.Tag);

		Protocol.SetProtocol<sc_base_replace_account> (sc_base_replace_account.Tag);

		Protocol.SetProtocol<sc_check_account_result> (sc_check_account_result.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_check_account_result.request> (sc_check_account_result.Tag);

		Protocol.SetProtocol<sc_club_apply_list> (sc_club_apply_list.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_club_apply_list.request> (sc_club_apply_list.Tag);

		Protocol.SetProtocol<sc_club_apply_ret> (sc_club_apply_ret.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_club_apply_ret.request> (sc_club_apply_ret.Tag);

		Protocol.SetProtocol<sc_club_create_ret> (sc_club_create_ret.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_club_create_ret.request> (sc_club_create_ret.Tag);

		Protocol.SetProtocol<sc_club_infolist> (sc_club_infolist.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_club_infolist.request> (sc_club_infolist.Tag);

		Protocol.SetProtocol<sc_club_join> (sc_club_join.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_club_join.request> (sc_club_join.Tag);

		Protocol.SetProtocol<sc_club_member_list> (sc_club_member_list.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_club_member_list.request> (sc_club_member_list.Tag);

		Protocol.SetProtocol<sc_club_newapply> (sc_club_newapply.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_club_newapply.request> (sc_club_newapply.Tag);

		Protocol.SetProtocol<sc_club_quit> (sc_club_quit.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_club_quit.request> (sc_club_quit.Tag);

		Protocol.SetProtocol<sc_coin_update> (sc_coin_update.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_coin_update.request> (sc_coin_update.Tag);

		Protocol.SetProtocol<sc_eliminate_finish> (sc_eliminate_finish.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_finish.request> (sc_eliminate_finish.Tag);

		Protocol.SetProtocol<sc_eliminate_game_reconnected> (sc_eliminate_game_reconnected.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_game_reconnected.request> (sc_eliminate_game_reconnected.Tag);

		Protocol.SetProtocol<sc_eliminate_map_info> (sc_eliminate_map_info.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_map_info.request> (sc_eliminate_map_info.Tag);

		Protocol.SetProtocol<sc_eliminate_map_start> (sc_eliminate_map_start.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_map_start.request> (sc_eliminate_map_start.Tag);

		Protocol.SetProtocol<sc_eliminate_op_ret> (sc_eliminate_op_ret.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_op_ret.request> (sc_eliminate_op_ret.Tag);

		Protocol.SetProtocol<sc_eliminate_op_step> (sc_eliminate_op_step.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_op_step.request> (sc_eliminate_op_step.Tag);

		Protocol.SetProtocol<sc_eliminate_otherplayerExit> (sc_eliminate_otherplayerExit.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_otherplayerExit.request> (sc_eliminate_otherplayerExit.Tag);

		Protocol.SetProtocol<sc_eliminate_playerExit> (sc_eliminate_playerExit.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_playerExit.request> (sc_eliminate_playerExit.Tag);

		Protocol.SetProtocol<sc_eliminate_reconnect> (sc_eliminate_reconnect.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_reconnect.request> (sc_eliminate_reconnect.Tag);

		Protocol.SetProtocol<sc_eliminate_round_info> (sc_eliminate_round_info.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_round_info.request> (sc_eliminate_round_info.Tag);

		Protocol.SetProtocol<sc_eliminate_useskill_ret> (sc_eliminate_useskill_ret.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_useskill_ret.request> (sc_eliminate_useskill_ret.Tag);

		Protocol.SetProtocol<sc_eliminate_useskill_step> (sc_eliminate_useskill_step.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_eliminate_useskill_step.request> (sc_eliminate_useskill_step.Tag);

		Protocol.SetProtocol<sc_enter_game> (sc_enter_game.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_enter_game.request> (sc_enter_game.Tag);

		Protocol.SetProtocol<sc_error_code> (sc_error_code.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_error_code.request> (sc_error_code.Tag);

		Protocol.SetProtocol<sc_error_warninfo> (sc_error_warninfo.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_error_warninfo.request> (sc_error_warninfo.Tag);

		Protocol.SetProtocol<sc_getcoin_recharge> (sc_getcoin_recharge.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_getcoin_recharge.request> (sc_getcoin_recharge.Tag);

		Protocol.SetProtocol<sc_recharge_success> (sc_recharge_success.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_recharge_success.request> (sc_recharge_success.Tag);

		Protocol.SetProtocol<sc_room_enter> (sc_room_enter.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_room_enter.request> (sc_room_enter.Tag);

		Protocol.SetProtocol<sc_room_match_cancel_ret> (sc_room_match_cancel_ret.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_room_match_cancel_ret.request> (sc_room_match_cancel_ret.Tag);

		Protocol.SetProtocol<sc_room_match_ret> (sc_room_match_ret.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_room_match_ret.request> (sc_room_match_ret.Tag);

		Protocol.SetProtocol<sc_room_otherplayer_enter> (sc_room_otherplayer_enter.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_room_otherplayer_enter.request> (sc_room_otherplayer_enter.Tag);

		Protocol.SetProtocol<sc_room_player_leave> (sc_room_player_leave.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_room_player_leave.request> (sc_room_player_leave.Tag);

		Protocol.SetProtocol<sc_room_ready> (sc_room_ready.Tag);
		Protocol.SetRequest<S2cSprotoType.sc_room_ready.request> (sc_room_ready.Tag);

	}

	public class gameplays2c_bagInfo {
		public const int Tag = 105;
	}

	public class gameplays2c_cashData {
		public const int Tag = 116;
	}

	public class gameplays2c_finishTutorial {
		public const int Tag = 120;
	}

	public class gameplays2c_gradeInfo {
		public const int Tag = 107;
	}

	public class gameplays2c_itemChange {
		public const int Tag = 102;
	}

	public class gameplays2c_levelUp {
		public const int Tag = 104;
	}

	public class gameplays2c_loginRewardState {
		public const int Tag = 113;
	}

	public class gameplays2c_notifyAllMail {
		public const int Tag = 122;
	}

	public class gameplays2c_notifyItemLimit {
		public const int Tag = 117;
	}

	public class gameplays2c_notifyNewMail {
		public const int Tag = 121;
	}

	public class gameplays2c_notifyWatchAd {
		public const int Tag = 118;
	}

	public class gameplays2c_offline {
		public const int Tag = 111;
	}

	public class gameplays2c_offlineAd {
		public const int Tag = 112;
	}

	public class gameplays2c_shareTaskInfo {
		public const int Tag = 114;
	}

	public class gameplays2c_slotData {
		public const int Tag = 110;
	}

	public class gameplays2c_slotReward {
		public const int Tag = 103;
	}

	public class gameplays2c_speedupInfo {
		public const int Tag = 109;
	}

	public class gameplays2c_syncData {
		public const int Tag = 101;
	}

	public class gameplays2c_taskInfo {
		public const int Tag = 108;
	}

	public class gameplays2c_tutorials {
		public const int Tag = 119;
	}

	public class gameplays2c_wheelData {
		public const int Tag = 115;
	}

	public class gameplays2c_workInfo {
		public const int Tag = 106;
	}

	public class sc_actor_eliminate_count_info {
		public const int Tag = 16;
	}

	public class sc_base_game_time {
		public const int Tag = 6;
	}

	public class sc_base_open_day {
		public const int Tag = 7;
	}

	public class sc_base_replace_account {
		public const int Tag = 8;
	}

	public class sc_check_account_result {
		public const int Tag = 10;
	}

	public class sc_club_apply_list {
		public const int Tag = 503;
	}

	public class sc_club_apply_ret {
		public const int Tag = 507;
	}

	public class sc_club_create_ret {
		public const int Tag = 506;
	}

	public class sc_club_infolist {
		public const int Tag = 500;
	}

	public class sc_club_join {
		public const int Tag = 501;
	}

	public class sc_club_member_list {
		public const int Tag = 502;
	}

	public class sc_club_newapply {
		public const int Tag = 505;
	}

	public class sc_club_quit {
		public const int Tag = 504;
	}

	public class sc_coin_update {
		public const int Tag = 13;
	}

	public class sc_eliminate_finish {
		public const int Tag = 406;
	}

	public class sc_eliminate_game_reconnected {
		public const int Tag = 410;
	}

	public class sc_eliminate_map_info {
		public const int Tag = 400;
	}

	public class sc_eliminate_map_start {
		public const int Tag = 405;
	}

	public class sc_eliminate_op_ret {
		public const int Tag = 404;
	}

	public class sc_eliminate_op_step {
		public const int Tag = 402;
	}

	public class sc_eliminate_otherplayerExit {
		public const int Tag = 411;
	}

	public class sc_eliminate_playerExit {
		public const int Tag = 412;
	}

	public class sc_eliminate_reconnect {
		public const int Tag = 409;
	}

	public class sc_eliminate_round_info {
		public const int Tag = 401;
	}

	public class sc_eliminate_useskill_ret {
		public const int Tag = 407;
	}

	public class sc_eliminate_useskill_step {
		public const int Tag = 408;
	}

	public class sc_enter_game {
		public const int Tag = 12;
	}

	public class sc_error_code {
		public const int Tag = 9;
	}

	public class sc_error_warninfo {
		public const int Tag = 11;
	}

	public class sc_getcoin_recharge {
		public const int Tag = 14;
	}

	public class sc_recharge_success {
		public const int Tag = 15;
	}

	public class sc_room_enter {
		public const int Tag = 300;
	}

	public class sc_room_match_cancel_ret {
		public const int Tag = 305;
	}

	public class sc_room_match_ret {
		public const int Tag = 304;
	}

	public class sc_room_otherplayer_enter {
		public const int Tag = 301;
	}

	public class sc_room_player_leave {
		public const int Tag = 302;
	}

	public class sc_room_ready {
		public const int Tag = 303;
	}

}